// Derived pointers only. Runs the installed, trusted TypeScript parser, never sampled source modules or script bodies.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import ts from '../portal/node_modules/typescript/lib/typescript.js';
import {fileURLToPath} from 'node:url';
const here=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
export const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
export function partFor(name,file){const s=name+' '+file;return /button|btn|버튼/i.test(s)?'버튼':/dialog|modal|sheet|drawer|popover/i.test(s)?'팝업·오버레이':/table|grid|list|pagination/i.test(s)?'표·목록':/input|select|check|radio|switch|form|field|picker/i.test(s)?'입력·선택':/toast|alert|badge|progress|skeleton|spinner|loading/i.test(s)?'상태·피드백':/nav|menu|tabs|sidebar|breadcrumb/i.test(s)?'메뉴·탐색':/chart|graph|plot/i.test(s)?'차트':/image|photo|video|audio|upload|avatar/i.test(s)?'이미지·미디어':/date|time|calendar/i.test(s)?'날짜·시간':/layout|card|box|section|panel|container/i.test(s)?'레이아웃·박스':'기타 부품';}
export function publicNames(source,file){const sf=ts.createSourceFile(file,source,ts.ScriptTarget.Latest,true,/\.[cm]?jsx?$/.test(file)?ts.ScriptKind.JSX:/x$/.test(file)?ts.ScriptKind.TSX:ts.ScriptKind.TS),result=[];
 const add=(name,node,kind)=>result.push({name,line:sf.getLineAndCharacterOfPosition(node.getStart(sf)).line+1,kind});
 for(const n of sf.statements){if(n.modifiers?.some(m=>m.kind===ts.SyntaxKind.ExportKeyword)){if((ts.isFunctionDeclaration(n)||ts.isClassDeclaration(n))&&n.name)add(n.name.text,n,'declaration');if(ts.isVariableStatement(n))for(const d of n.declarationList.declarations)if(ts.isIdentifier(d.name))add(d.name.text,d,'value');}
 if(ts.isExportDeclaration(n)&&!n.isTypeOnly&&n.exportClause&&ts.isNamedExports(n.exportClause))for(const e of n.exportClause.elements)if(!e.isTypeOnly)add(e.name.text,n,n.moduleSpecifier?'reexport':'alias');}
 return {names:result,parseErrors:sf.parseDiagnostics.length};}
export function safePackage(doc){const deps=[];for(const section of ['dependencies','devDependencies','peerDependencies','optionalDependencies'])for(const [name,raw] of Object.entries(doc[section]||{})){if(!/^(?:@[a-z0-9._-]+\/)?[a-z0-9._-]+$/i.test(name))continue;const v=typeof raw==='string'&&raw.length<100&&/^[0-9a-z~^<>=*| .+_-]+$/i.test(raw)&&!raw.includes('token')?raw:'비공개·로컬·URL 지정';deps.push({name,version:v,section});}return {dependencies:deps,scriptNames:Object.keys(doc.scripts||{}).filter(n=>/^[a-z0-9:_-]{1,60}$/i.test(n))};}
export function collect(input,root){const assets=[],manifests=[],issues=[],dirs=new Set(),audit={current:0,changed:0,missing:0,linked:0,outside:0};const rootPath=path.resolve(root),canonicalRoot=fs.realpathSync(rootPath).toLowerCase();
 function inRoot(file){const absolute=path.resolve(file);if(!absolute.toLowerCase().startsWith(rootPath.toLowerCase()+path.sep))return false;const real=fs.realpathSync(absolute).toLowerCase();return real.startsWith(canonicalRoot+path.sep)&&real===absolute.toLowerCase();}
 const validProjects=input.projects.filter(p=>typeof p.name==='string'&&p.name!=='.'&&p.name!=='..'&&!path.isAbsolute(p.name)&&path.basename(p.name)===p.name);for(const p of input.projects)if(!validProjects.includes(p)){audit.outside++;issues.push({path:String(p.name),reason:'invalid_project_path'});}
 for(const m of input.modules){const file=path.resolve(root,m.path);if(!file.startsWith(path.resolve(root)+path.sep)){audit.outside++;issues.push({path:m.path,reason:'outside_root'});continue;}let dir=path.dirname(file);while(dir.startsWith(path.resolve(root)+path.sep)){dirs.add(dir);dir=path.dirname(dir);}
 let bytes;try{if(!inRoot(file)){audit.linked++;issues.push({path:m.path,reason:'linked_or_outside_canonical_root'});continue;}bytes=fs.readFileSync(file);}catch{audit.missing++;issues.push({path:m.path,reason:'missing_or_unreadable'});continue;}
 if(hash(bytes)!==m.sha256){audit.changed++;issues.push({path:m.path,reason:'source_changed_since_inventory'});continue;}audit.current++;
 if(!/\.[cm]?[jt]sx?$/.test(file))continue;
 const parsed=publicNames(bytes.toString('utf8'),file);if(parsed.parseErrors){issues.push({path:m.path,reason:'parse_errors'});continue;}
 for(const e of parsed.names){assets.push({id:hash(m.path+':'+e.name+':'+e.line).slice(0,16),project:m.project,path:m.path,sha256:m.sha256,...e,group:/^use[A-Z]/.test(e.name)?'상태·훅':/components\/|\/ui\//.test(m.path)?'UI 공개 심볼':'기능·공개 심볼',part:partFor(e.name,m.path),status:'candidate',runtimeVerified:false});}
 }
 for(const p of validProjects)dirs.add(path.resolve(root,p.name));
 for(const dir of [...dirs].sort()){const file=path.join(dir,'package.json');if(!fs.existsSync(file))continue;try{if(!inRoot(file)){issues.push({path:path.relative(root,file).replaceAll('\\','/'),reason:'manifest_linked_or_outside_root'});continue;}const bytes=fs.readFileSync(file);if(bytes.length>1000000)continue;const doc=JSON.parse(bytes),relative=path.relative(root,file).replaceAll('\\','/');manifests.push({path:relative,project:relative.split('/')[0],sha256:hash(bytes),...safePackage(doc)});}catch{issues.push({path:path.relative(root,file).replaceAll('\\','/'),reason:'manifest_read_or_parse_failed'});}}
 const packages=new Map();for(const m of manifests)for(const d of m.dependencies){const item=packages.get(d.name)||{name:d.name,uses:[]};item.uses.push({...d,path:m.path,project:m.project,sha256:m.sha256});packages.set(d.name,item);}
 return {kind:'derived_toolbox_not_authority',capturedAt:new Date().toISOString(),functionSnapshot:input.capturedAt,coverage:{projects:validProjects.length,modules:input.modules.length,...audit,publicSymbols:assets.length,manifests:manifests.length,packages:packages.size},limitations:['JS/TS 파일의 최상위 공개 값·함수·클래스·이름 있는 재수출을 색인합니다. type-only·export *·익명 default·중첩 export·Python 공개 API는 이 도구의 심볼 목록에서 제외됩니다.','폴더명 기반 그룹은 후보입니다. React 부품 여부·실사용·실행 합격 판정이 아닙니다.','연결 파일·연결 폴더와 조사 루트 밖 경로는 읽지 않으며 예외 목록에 남깁니다.','의존성은 package.json 선언입니다. 설치·잠금 버전·라이선스·보안 검증을 대신하지 않습니다.','기능 수집에 포함된 프로젝트와 소스 상위 경로의 package.json만 조사합니다. 소스 없는 깊은 패키지와 제외 경로는 미조사입니다.','원본 코드를 실행하거나 외부 패키지를 설치하지 않습니다. 명령 본문·자격 증명·의존성 URL은 내보내지 않습니다.'],projects:validProjects.map(p=>({name:p.name,head:p.head,dirty:p.dirty})),assets,manifests,packages:[...packages.values()].sort((a,b)=>a.name.localeCompare(b.name)),issues};}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){const file=path.resolve(process.argv[2]||path.join(here,'portal/public/catalog/functions.json'));const input=JSON.parse(fs.readFileSync(file));const root=path.resolve(here,'..');if(path.resolve(input.scope)!==root)throw Error('Inventory scope differs from authorized development root');const result=collect(input,root);const out=process.argv[3]||path.join(here,'portal/public/catalog/toolbox.json');fs.writeFileSync(out,JSON.stringify(result));console.log(JSON.stringify(result.coverage));}
