// Actual Chromium interactions; never converts untested criteria to PASS.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const runtime=process.env.DEVCENTER_PLAYWRIGHT||path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {chromium}=require(runtime);
let activeBrowser;
(async()=>{
 const {sourceDigest,sha}=await import('./acceptance-evidence.mjs');const before=sourceDigest(),app=sha(fs.readFileSync(path.join(root,'portal/static/app.js'))),checks={};
 const browser=activeBrowser=await chromium.launch({headless:true,executablePath:process.env.DEVCENTER_CHROMIUM||path.join(process.env.LOCALAPPDATA,'ms-playwright/chromium-1148/chrome-win/chrome.exe')});
 const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write']});await context.tracing.start({screenshots:true,snapshots:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const url='http://127.0.0.1:4317/';await page.goto(url);page.setDefaultTimeout(12000);
 async function go(label){const toggle=page.getByRole('button',{name:'메뉴 열기',exact:true});if(await toggle.isVisible())await toggle.click();await page.getByRole('button',{name:label,exact:true}).click();}
 async function check(id,description,fn){try{await fn();checks[id]={status:'PASS',description};console.log(id+' PASS')}catch(e){checks[id]={status:'FAIL',description,error:String(e.message)};console.log(id+' FAIL '+e.message.slice(0,140))}}
 async function visible(locator){await locator.waitFor({state:'visible'});assert(await locator.isVisible())}
 await check('L01','Tour steps and other-session request clipboard verified',async()=>{await go('세션 견학');await visible(page.getByRole('heading',{name:'다른 세션을 위한 개발센터 견학',exact:true}));await page.getByRole('button',{name:'다른 세션용 요청 복사',exact:true}).click();await visible(page.getByText('요청문 복사됨',{exact:true}));});
 await check('I01','Catalog, CSS and function list opened through menu',async()=>{for(const [nav,label]of [['전체 규격 찾기','규격 검색'],['CSS 스타일 창고','CSS 검색'],['기능 창고','전체 프로젝트 기능 검색']]){await go(nav);await visible(page.getByRole('textbox',{name:label,exact:true}));}});
 await check('I07','Global kmValue search and project selection',async()=>{await page.getByLabel('전체 프로젝트 기능 검색',{exact:true}).fill('kmValue');await page.getByRole('button',{name:'전체 기능 검색',exact:true}).click();await page.getByRole('button',{name:'kmValue freepasserp4/lib/format.ts:89',exact:true}).click();assert.equal(await page.getByLabel('기능 프로젝트',{exact:true}).inputValue(),'freepasserp4');});
 await check('R03','Formatting group, declaration selection and original-reference clipboard',async()=>{await page.getByLabel('기능 그룹',{exact:true}).selectOption({label:'표기·변환'});await page.getByRole('button',{name:'kmValue freepasserp4/lib/format.ts:89 표기·변환 · 선언 발견',exact:true}).click();await page.getByRole('button',{name:'원본 참조 복사',exact:true}).click();});
 await check('R01','Input and return annotations visible',async()=>{await visible(page.getByText('UnknownKeyword',{exact:false}));await visible(page.getByText('NumberKeyword',{exact:false}));});
 await check('R02','Module references explicitly distinguished from runtime evidence',async()=>{await visible(page.getByText('모듈 import 근거이며 선택한 함수의 호출·실행 증거는 아닙니다.',{exact:false}));});
 await check('R04','8.3만km -> 83000, 1024 bytes -> 1KB from original functions',async()=>{await page.getByText('원본 기능 직접 써보기 — 주행거리·파일 크기',{exact:true}).click();await page.getByLabel('주행거리 기능 입력').fill('8.3만km');await page.getByLabel('파일 크기 기능 입력').fill('1024');await visible(page.getByText('kmValue → 83000',{exact:true}));await visible(page.getByText('fileSizeText → 1KB',{exact:true}));});
 await check('R05','Complete recipe clipboard contains original import and numeric bytes conversion',async()=>{await page.getByText('재사용 계약과 완결된 예제',{exact:true}).click();await page.getByRole('button',{name:'기능 예제 복사',exact:true}).click();const clip=await page.evaluate(()=>navigator.clipboard.readText());assert(clip.includes("from '@/lib/format'"));assert(clip.includes('fileSizeText(Number(rawBytes))'));});
 await check('R06','Source, numeric-byte input, side effects and dependencies displayed',async()=>{for(const text of ['숫자 바이트','저장·API·외부 전송을 수행하지 않습니다.','FP4 내부용'])await visible(page.getByText(text,{exact:false}));});
 await check('S03','Separate card structure, source, tests, independent review and approval stages',async()=>{await go('규격 카드·학습');for(const text of ['필수 내용 작성','원본 해시 일치','연결 검사 통과','독립 검토 완료','정식 승인'])await visible(page.getByText(text,{exact:true}));});
 await check('L02','Button card search and selection',async()=>{await page.getByLabel('규격 카드 검색').fill('버튼');await page.getByRole('button',{name:/^버튼 형태·크기·상태 FP4/}).click();await visible(page.getByRole('heading',{name:'버튼 형태·크기·상태',exact:true}));});
 await check('L05','Wrong answer leads back to SSOT card',async()=>{await page.getByRole('radio',{name:'사본을 정본으로 즉시 승격한다',exact:true}).check();await page.getByRole('button',{name:'학습 결과 확인',exact:true}).click();await page.getByRole('button',{name:'관련 카드 보기',exact:true}).first().click();await visible(page.getByRole('heading',{name:'정본과 사본을 구별하기',exact:true}));});
 await check('L07','Export contains question hash, answer and non-certification; actual clipboard parsed',async()=>{await page.getByRole('button',{name:'학습 결과 복사',exact:true}).click();const clip=JSON.parse(await page.evaluate(()=>navigator.clipboard.readText()));assert.match(clip.questionVersion,/^[a-f0-9]{64}$/);assert.equal(Object.keys(clip.answers).length,1);assert.equal(clip.result.certification,false);});
 await check('L06','Empty six-field plan rejected and filled plan stays review-pending',async()=>{await page.getByRole('button',{name:'계획 누락 확인',exact:true}).click();await visible(page.getByText('보완할 항목 6개',{exact:true}));for(const label of ['대상 프로젝트','요청과 완료 조건','기준 원본 경로','원본 버전 또는 작업 트리 상태','재사용할 자산 또는 신규 제작 이유','검증할 입력·기대 결과·증거 위치'])await page.getByLabel(label,{exact:true}).fill('자동 브라우저 시험 '+label);await page.getByRole('button',{name:'계획 누락 확인',exact:true}).click();await visible(page.getByText('필수 칸 작성됨 · 내용 검토 대기',{exact:true}));});
 await check('L08','Draft cannot grant approval or source verification',async()=>{await page.getByRole('button',{name:'작업 계획 복사',exact:true}).click();const clip=JSON.parse(await page.evaluate(()=>navigator.clipboard.readText()));assert.equal(clip.check.approved,false);assert.equal(clip.check.sourceVerified,false);});
 await check('S07','Button card opens appropriate source specimen',async()=>{await page.getByRole('button',{name:/^버튼 형태·크기·상태 FP4/}).click();await page.getByRole('button',{name:'관련 화면에서 확인',exact:true}).click();assert((await page.locator('iframe').getAttribute('src')).includes('kind=buttons'));});
 await check('D06','Usage clipboard and source hash shown separately',async()=>{await page.getByText('사용 코드',{exact:true}).click();await page.getByRole('button',{name:'코드 복사',exact:true}).click();await visible(page.getByText('복사됨',{exact:true}));await page.getByText('원본 코드',{exact:true}).click();await visible(page.getByText('SHA c186ed2556dc',{exact:false}));});
 await check('S06','Source conflict with unresolved expected behavior visible',async()=>{await page.getByRole('button',{name:'충돌과 근거 보기',exact:true}).click();await visible(page.getByRole('heading',{name:'표 주석과 클릭 동작',exact:true}));});
 await check('D07','No-result query and reset restore catalog rows',async()=>{await go('전체 규격 찾기');await page.getByLabel('규격 검색').fill('ZZZ_NO_MATCH_73d2');await visible(page.getByText('일치하는 규격이 없습니다.',{exact:true}));await page.getByRole('button',{name:'필터 해제',exact:true}).click();assert(await page.locator('.doc-row').count()>0);});
 await check('D01','Menu switches academy, functions, CSS and laboratory',async()=>{for(const name of ['규격 카드·학습','기능 창고','CSS 스타일 창고','원자 실험실']){await go(name);await visible(page.locator('h1'));}});
 const spec=await context.newPage();
 await check('D02','Button variant/size click and actual disabled property',async()=>{await spec.goto(url+'specimen/index.html?kind=buttons');await spec.getByLabel('버튼 형태').selectOption('danger');await spec.getByLabel('버튼 크기').selectOption('lg');await spec.getByRole('button',{name:'저장하기',exact:true}).click();await visible(spec.getByText('danger / lg 선택됨',{exact:true}));await spec.getByLabel('버튼 비활성').check();assert(await spec.getByRole('button',{name:'저장하기',exact:true}).isDisabled());});
 await check('D03','Input/select/check updates combined output',async()=>{await spec.goto(url+'specimen/index.html?kind=inputs');await spec.getByLabel('원자 이름',{exact:true}).fill('검사 입력');await spec.getByLabel('검토 상태').selectOption('보류');await spec.getByLabel('규격 확인').check();await visible(spec.getByText('검사 입력 · 보류 · 확인 체크됨',{exact:true}));});
 await check('D04','Row callback and empty-table output',async()=>{await spec.goto(url+'specimen/index.html?kind=table');await spec.getByRole('button',{name:'DataTable 표 table.tsx 클릭 확인',exact:true}).click();await visible(spec.getByText('DataTable 선택 · onRow 1회 호출',{exact:true}));await spec.getByLabel('빈 표 보기').check();await visible(spec.getByText('표시할 행이 없습니다.',{exact:true}));});
 await check('D05','FormCard input and output',async()=>{await spec.goto(url+'specimen/index.html?kind=box');await spec.getByLabel('폼 원자 이름').fill('폼 검사');await spec.getByRole('button',{name:'입력 확인',exact:true}).click();await visible(spec.getByText('폼 검사 입력을 확인했습니다.',{exact:true}));});
 await check('D08','Real Chromium 1440px and 390px viewport, menu/body and document overflow checked',async()=>{for(const width of [1440,390]){await page.setViewportSize({width,height:1000});await go('디자인 도구 실습');await visible(page.getByLabel('대비 글자색'));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await page.screenshot({path:path.join(root,`reviews/expansion-${width}.png`),fullPage:true});}});
 await check('EXPANSION','Toolbox filter/reset; contrast, rem, grid and formatting examples',async()=>{await page.setViewportSize({width:1440,height:1000});await go('부품·개발 도구 모음');await page.getByLabel('도구 모음 검색').fill('Button');assert(await page.locator('.doc-row').count()>0);await page.getByLabel('도구 모음 검색').fill('NO_MATCH_78sd');await page.getByRole('button',{name:'도구 필터 초기화'}).click();assert(await page.locator('.doc-row').count()>0);await page.getByLabel('도구 모음 종류').selectOption('packages');await page.getByLabel('도구 모음 검색').fill('react');assert(await page.locator('details').count()>1);await go('디자인 도구 실습');await page.getByLabel('대비 글자색').fill('#000000');await visible(page.getByText('대비 21.00:1',{exact:false}));await page.getByLabel('대비 글자색').fill('bad');await visible(page.getByRole('alert'));await page.getByLabel('환산 픽셀').fill('32');await visible(page.getByText('32px = 2rem',{exact:true}));await page.getByLabel('격자 간격').fill('24');await page.getByRole('button',{name:'격자 예제 복사'}).click();assert((await page.evaluate(()=>navigator.clipboard.readText())).includes('gap: 24px'));await go('기능 창고');await page.getByText('금액·주행거리·연료 표기 비교 — 원본 기능 5개',{exact:true}).click();await visible(page.getByRole('cell',{name:'39만 8,000원',exact:true}));});
 await check('L10','Persistent sessions, practice failures, stale-version relearning, validated transfer, concurrent writes and corrupt-storage preservation',async()=>{
  await go('규격 카드·학습');
  await page.getByRole('radio',{name:'사본을 정본으로 즉시 승격한다',exact:true}).check();
  await page.getByLabel('이력 세션 이름').fill('session A');await page.getByRole('button',{name:'현재 답안 이력 저장',exact:true}).click();await visible(page.getByRole('heading',{name:'보관 1건 · 재학습·보완 대상 1건',exact:true}));
  await page.reload();await go('규격 카드·학습');await visible(page.getByRole('heading',{name:'보관 1건 · 재학습·보완 대상 1건',exact:true}));
  await page.getByLabel('이력 세션 이름').fill('session B');
  for(const label of ['대상 프로젝트','요청과 완료 조건','기준 원본 경로','원본 버전 또는 작업 트리 상태','재사용할 자산 또는 신규 제작 이유','검증할 입력·기대 결과·증거 위치'])await page.getByLabel(label,{exact:true}).fill('시험 근거 '+label);
  await page.getByLabel('실습 실행 결과').selectOption('failed');await page.getByRole('button',{name:'현재 실습 이력 저장',exact:true}).click();await visible(page.getByRole('alert'));
  await page.getByLabel('실습 실행 근거').fill('local fixture test failed at assertion 8');await page.getByRole('button',{name:'현재 실습 이력 저장',exact:true}).click();await visible(page.getByRole('heading',{name:'보관 2건 · 재학습·보완 대상 2건',exact:true}));
  const key='devcenter.learning-history.v1',raw=await page.evaluate(k=>localStorage.getItem(k),key),saved=JSON.parse(raw);assert.equal(saved.records[1].outcome,'failed');assert(!('approved' in saved.records[1]));
  await page.getByText('다른 세션에 전달·가져오기',{exact:true}).click();
  const old={...saved.records[0],id:'33333333-1234-1234-1234-123456789abc',questionVersion:'b'.repeat(64),session:'old session',answers:{obsolete:0}};
  await page.getByLabel('가져올 학습 이력 JSON').fill(JSON.stringify({version:1,records:[old]}));await page.getByRole('button',{name:'검사 후 이력 합치기',exact:true}).click();await visible(page.getByText(/old session.*문제 버전 변경 · 재학습 필요/));
  await page.getByLabel('가져올 학습 이력 JSON').fill(JSON.stringify({version:1,records:[{...old,approved:true}]}));await page.getByRole('button',{name:'검사 후 이력 합치기',exact:true}).click();await visible(page.getByRole('alert'));assert.equal(JSON.parse(await page.evaluate(k=>localStorage.getItem(k),key)).records.length,3);
  await page.getByRole('button',{name:'저장 이력 원문 복사',exact:true}).click();const backup=await page.evaluate(()=>navigator.clipboard.readText());assert.equal(JSON.parse(backup).records.length,3);
  const otherContext=await browser.newContext({viewport:{width:1440,height:1000}}),other=await otherContext.newPage();await other.goto(url);await other.getByRole('button',{name:'규격 카드·학습',exact:true}).click();await other.getByText('다른 세션에 전달·가져오기',{exact:true}).click();await other.getByLabel('가져올 학습 이력 JSON').fill(backup);await other.getByRole('button',{name:'검사 후 이력 합치기',exact:true}).click();await visible(other.getByRole('heading',{name:'보관 3건 · 재학습·보완 대상 3건',exact:true}));await otherContext.close();
  const second=await context.newPage();await second.goto(url);await second.getByRole('button',{name:'규격 카드·학습',exact:true}).click();await second.getByLabel('이력 세션 이름').fill('concurrent C');await page.getByLabel('이력 세션 이름').fill('concurrent D');await Promise.all([second.getByRole('button',{name:'현재 답안 이력 저장',exact:true}).click(),page.getByRole('button',{name:'현재 답안 이력 저장',exact:true}).click()]);await visible(page.getByRole('heading',{name:'보관 5건 · 재학습·보완 대상 5건',exact:true}));await second.close();
  await page.evaluate(k=>localStorage.setItem(k,'{broken'),key);await page.reload();await go('규격 카드·학습');await visible(page.getByRole('alert'));assert(await page.getByRole('button',{name:'현재 답안 이력 저장',exact:true}).isDisabled());assert.equal(await page.evaluate(k=>localStorage.getItem(k),key),'{broken');await page.getByText('가득 찼거나 손상된 이력 보관하기',{exact:true}).click();await page.getByRole('button',{name:'원문 백업 후 새 묶음 시작',exact:true}).click();await visible(page.getByRole('heading',{name:'보관 0건 · 재학습·보완 대상 0건',exact:true}));assert(await page.evaluate(k=>Object.keys(localStorage).filter(x=>x.startsWith(k+'.backup.')).some(x=>localStorage.getItem(x)==='{broken'),key));await page.evaluate(({key,backup})=>localStorage.setItem(key,backup),{key,backup});await page.reload();await go('규격 카드·학습');await visible(page.getByRole('heading',{name:'보관 3건 · 재학습·보완 대상 3건',exact:true}));
 });
 await check('HISTORY_RECOVERY','Malformed catalogs and wrong question hashes show retry instead of render crash; storage quota failure keeps original bytes',async()=>{
  const original=JSON.parse(fs.readFileSync(path.join(root,'portal/static/catalog/standard-cards.json'),'utf8'));
  for(const bad of [{},{...original,questionVersion:'0'.repeat(64)}]){await page.route('**/catalog/standard-cards.json',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify(bad)}));await go('디자인 도구 실습');await go('규격 카드·학습');await visible(page.getByRole('alert'));await page.unroute('**/catalog/standard-cards.json');await page.getByRole('button',{name:'다시 불러오기',exact:true}).click();await visible(page.getByRole('heading',{name:'세션별 학습·실습 이력',exact:true}));}
  const key='devcenter.learning-history.v1',before=await page.evaluate(k=>localStorage.getItem(k),key);await page.evaluate(()=>{window.__originalSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw new DOMException('Quota exceeded','QuotaExceededError')}});await page.getByLabel('이력 세션 이름').fill('quota test');await page.getByRole('button',{name:'현재 답안 이력 저장',exact:true}).click();await visible(page.getByRole('alert'));assert.equal(await page.evaluate(k=>localStorage.getItem(k),key),before);await page.evaluate(()=>{Storage.prototype.setItem=window.__originalSetItem;delete window.__originalSetItem});
 });
 await check('DISCOVERY','Three live teaching models, six guides, source hash, clipboard, empty filter, retry and responsive view',async()=>{
  await go('몰랐던 개발 기술');await page.getByRole('button',{name:'A 저장',exact:true}).click();await page.getByRole('button',{name:'B 저장',exact:true}).click();await visible(page.getByText('충돌 차단: 원본을 다시 읽고 두 변경의 차이를 검토하세요.',{exact:true}));assert((await page.getByLabel('동시 수정 원본').innerText()).includes('AI A의 제목'));await page.getByRole('button',{name:'B 원본 다시 읽기',exact:true}).click();assert.equal(await page.getByLabel('AI B 수정 내용').inputValue(),'AI B의 제목');await page.getByLabel('AI B 수정 내용').fill('A와 B를 병합한 제목');await page.getByRole('button',{name:'B 저장',exact:true}).click();assert((await page.getByLabel('동시 수정 원본').innerText()).includes('A와 B를 병합한 제목'));
  await page.getByRole('checkbox',{name:'버전 검사 켜기',exact:true}).uncheck();await page.getByRole('button',{name:'동시 수정 초기화',exact:true}).click();await page.getByRole('button',{name:'A 저장',exact:true}).click();await page.getByRole('button',{name:'B 저장',exact:true}).click();assert((await page.getByLabel('동시 수정 원본').innerText()).includes('AI B의 제목'));
  await page.getByRole('button',{name:/^재시도해도 한 번만/}).click();await page.getByRole('button',{name:'같은 저장 요청 보내기',exact:true}).evaluate(b=>{b.click();b.click()});await visible(page.getByText('생성된 기록 1건',{exact:true}));await page.getByLabel('실험 요청 내용').fill('changed');await page.getByRole('button',{name:'같은 저장 요청 보내기',exact:true}).click();await visible(page.getByText('같은 표식인데 내용이 다릅니다 · 요청 충돌',{exact:true}));await page.getByRole('checkbox',{name:'중복 요청 검사 켜기',exact:true}).uncheck();await page.getByRole('button',{name:'중복 요청 초기화',exact:true}).click();await page.getByRole('button',{name:'같은 저장 요청 보내기',exact:true}).evaluate(b=>{b.click();b.click()});await visible(page.getByText('생성된 기록 2건',{exact:true}));
  await page.getByRole('button',{name:/^늦게 온 응답 다루기/}).click();for(const guard of [true,false]){await page.getByRole('checkbox',{name:'최신 요청 응답만 반영',exact:true}).setChecked(guard);await page.getByRole('button',{name:'응답 실험 초기화',exact:true}).click();for(const word of ['old','new']){await page.getByLabel('응답 실험 검색어').fill(word);await page.getByRole('button',{name:'검색 요청 만들기',exact:true}).click();}await page.getByRole('button',{name:'2번 응답 도착 · new',exact:true}).click();await page.getByRole('button',{name:'1번 응답 도착 · old',exact:true}).click();assert.equal(await page.getByLabel('현재 검색 결과').innerText(),'화면 결과 · '+(guard?'new':'old'));}
  await page.getByLabel('새 기술 검색').fill('상태 머신');await page.getByRole('button',{name:/^불가능한 상태를 없애기/}).click();await visible(page.getByText('이 파트는 아직 실행 실험이 없습니다.',{exact:false}));await page.getByRole('button',{name:'AI에게 줄 적용 계획 복사',exact:true}).click();const clip=JSON.parse(await page.evaluate(()=>navigator.clipboard.readText()));assert.equal(clip.approved,false);assert.equal(clip.concept,'상태 머신');await page.getByLabel('새 기술 검색').fill('zzzz_no_topic');await page.getByRole('button',{name:'새 기술 필터 초기화',exact:true}).click();
  await page.getByText('세 실험의 실제 코드와 출처',{exact:true}).click();const source=await (await page.request.get(url+'catalog/discovery-source.json')).json();assert.equal(source.sha256,sha(fs.readFileSync(path.join(root,'portal/app/discovery-model.ts'))));await visible(page.getByText(source.source,{exact:true}));
  await page.route('**/catalog/discovery-source.json',r=>r.fulfill({status:503,body:'unavailable'}));await go('디자인 도구 실습');await go('몰랐던 개발 기술');await page.getByText('세 실험의 실제 코드와 출처',{exact:true}).click();await visible(page.getByRole('alert'));await page.unroute('**/catalog/discovery-source.json');await page.getByRole('button',{name:'실험 원본 다시 읽기',exact:true}).click();await visible(page.getByText(source.source,{exact:true}));
  await page.route('**/catalog/discovery-source.json',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({...source,source:source.source+'\n// mismatched build',sha256:sha(source.source+'\n// mismatched build')})}));await go('디자인 도구 실습');await go('몰랐던 개발 기술');await page.getByText('세 실험의 실제 코드와 출처',{exact:true}).click();await visible(page.getByText('실험 원본 해시 불일치',{exact:true}));await page.unroute('**/catalog/discovery-source.json');await page.getByRole('button',{name:'실험 원본 다시 읽기',exact:true}).click();await visible(page.getByText(source.source,{exact:true}));
  for(const width of [1440,390]){const visualContext=await browser.newContext({viewport:{width,height:1000}});try{const visualPage=await visualContext.newPage();await visualPage.goto(url);if(width<767)await visualPage.getByRole('button',{name:'메뉴 열기',exact:true}).click();await visualPage.getByRole('button',{name:'몰랐던 개발 기술',exact:true}).click();await visible(visualPage.getByRole('button',{name:'A 저장',exact:true}));assert(await visualPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await visualPage.screenshot({path:path.join(root,`reviews/discovery-${width}.png`),fullPage:false,timeout:15000});}finally{await visualContext.close()}}
 });
 await check('SEARCH_RECOVERY','Enter search, malformed index retry and obsolete responses after query edit',async()=>{
  const pattern='**/catalog/function-search.json',fixture={modules:[['demo/source.ts','demo']],entries:[['older',0,1],['newer',0,2]]};
  await go('디자인 도구 실습');await go('기능 창고');let count=0;
  await page.route(pattern,r=>{count++;return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify(count===1?{modules:[],entries:[['broken',0,1]]}:fixture)})});
  await page.getByLabel('전체 프로젝트 기능 검색').fill('newer');await page.getByLabel('전체 프로젝트 기능 검색').press('Enter');await visible(page.getByText('전체 기능 색인의 형식이 잘못되었습니다. 다시 검색해 주세요.',{exact:true}));await page.getByLabel('전체 프로젝트 기능 검색').press('Enter');await visible(page.getByRole('button',{name:'newer demo/source.ts:2',exact:true}));assert.equal(count,2);await page.unroute(pattern);
  await go('디자인 도구 실습');await go('기능 창고');
  // Ignore abort only in this isolated test so an obsolete response really reaches JS.
  await page.evaluate(()=>{window.__searchFetch=window.fetch;window.fetch=(input,init)=>String(input).includes('/catalog/function-search.json')?window.__searchFetch(input,{...init,signal:undefined}):window.__searchFetch(input,init)});
  let release,finished;const delayed=new Promise(r=>release=r),settled=new Promise(r=>finished=r);count=0;
  await page.route(pattern,async r=>{count++;if(count===1){await delayed;try{await r.fulfill({status:200,contentType:'application/json',body:JSON.stringify(fixture)})}finally{finished()}}else await r.fulfill({status:200,contentType:'application/json',body:JSON.stringify(fixture)})});
  await page.getByLabel('전체 프로젝트 기능 검색').fill('older');const firstRequest=page.waitForRequest(r=>r.url().endsWith('/catalog/function-search.json'));await page.getByLabel('전체 프로젝트 기능 검색').press('Enter');await firstRequest;
  await page.getByLabel('전체 프로젝트 기능 검색').fill('newer');await page.getByLabel('전체 프로젝트 기능 검색').press('Enter');await visible(page.getByRole('button',{name:'newer demo/source.ts:2',exact:true}));release();await settled;
  await page.evaluate(async()=>{await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))});assert.equal(await page.getByRole('button',{name:'older demo/source.ts:1',exact:true}).count(),0);await visible(page.getByRole('button',{name:'newer demo/source.ts:2',exact:true}));
  await page.getByLabel('전체 프로젝트 기능 검색').fill('x');assert.equal(await page.getByRole('button',{name:'newer demo/source.ts:2',exact:true}).count(),0);await page.getByLabel('전체 프로젝트 기능 검색').press('Enter');await visible(page.getByText('두 글자 이상 입력하세요.',{exact:true}));await page.unroute(pattern);await page.evaluate(()=>{window.fetch=window.__searchFetch;delete window.__searchFetch});
 });
 await check('CATALOG_RECOVERY','Catalog HTTP, JSON, cross-reference and bundled source-hash failures show one retry path without render crashes',async()=>{
  const sourceCode=JSON.parse(fs.readFileSync(path.join(root,'portal/static/catalog/source-code.json'),'utf8'));
  const tampered=structuredClone(sourceCode);tampered.buttons.source+='\n/* changed together with declared hash */';tampered.buttons.sha256=sha(tampered.buttons.source);
  const cases=[
   {pattern:'**/catalog/index.json',status:200,body:JSON.stringify({}),message:'규격 목록의 자료 형식이 올바르지 않습니다. 다시 불러오세요.'},
   {pattern:'**/catalog/atomic-audit.json',status:200,body:'{broken',message:'원자 대조 자료의 JSON을 읽지 못했습니다. 다시 불러오세요.'},
   {pattern:'**/catalog/source-code.json',status:200,body:JSON.stringify(tampered),message:'원본 코드의 자료 형식이 올바르지 않습니다. 다시 불러오세요.'},
   {pattern:'**/catalog/index.json',status:503,body:'unavailable',message:'규격 목록 자료를 불러오지 못했습니다. 다시 시도하세요.'},
  ];
  for(const item of cases){
   const localContext=await browser.newContext({viewport:{width:1200,height:900}});try{const localPage=await localContext.newPage();const localErrors=[];localPage.on('pageerror',e=>localErrors.push(e.message));let calls=0;
    await localPage.route(item.pattern,r=>++calls===1?r.fulfill({status:item.status,contentType:'application/json',body:item.body}):r.continue());await localPage.goto(url);await localPage.getByRole('button',{name:'전체 규격 찾기',exact:true}).click();await localPage.getByRole('alert').waitFor({state:'visible'});assert((await localPage.getByRole('alert').innerText()).includes(item.message));await localPage.getByRole('button',{name:'다시 불러오기',exact:true}).click();await localPage.getByLabel('규격 검색').waitFor({state:'visible'});assert(await localPage.locator('.doc-row').count()>0);assert.equal(localErrors.length,0);assert.equal(calls,2);
   }finally{await localContext.close()}}
 });
 await check('INSPECTION','Control room renders evidence, preserves HOLD, exports a bounded work order and reflows at 390px',async()=>{await page.setViewportSize({width:1440,height:1000});await go('지도점검 관제실');await visible(page.getByRole('heading',{name:'개발센터가 점검하고, 시정하고, 다시 검사합니다.',exact:true}));await visible(page.getByText('판정 보류',{exact:true}).first());await page.getByRole('button',{name:'전체 시정 지시서 복사',exact:true}).click();const order=JSON.parse(await page.evaluate(()=>navigator.clipboard.readText()));assert.equal(order.kind,'devcenter_corrective_work_order_v1');assert(order.findings.length>0);assert.equal(order.completion,'new_hash_and_recheck_required');assert(order.findings.every(x=>x.id&&x.evidence.length&&x.requiredAction&&x.recheck));await page.setViewportSize({width:390,height:1000});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await visible(page.getByRole('heading',{name:'개발센터가 점검하고, 시정하고, 다시 검사합니다.',exact:true}));await page.setViewportSize({width:1440,height:1000});});
 await check('INSPECTION_RECOVERY','Malformed or contradictory inspection data is rejected and retry restores the control room',async()=>{const source=JSON.parse(fs.readFileSync(path.join(root,'portal/static/catalog/inspection.json'),'utf8')),contradictory=structuredClone(source);contradictory.summary.overall='PASS';for(const body of ['{}',JSON.stringify(contradictory)]){const localContext=await browser.newContext({viewport:{width:1200,height:900}});try{const localPage=await localContext.newPage();let calls=0;await localPage.route('**/catalog/inspection.json',r=>++calls===1?r.fulfill({status:200,contentType:'application/json',body}):r.continue());await localPage.goto(url);await localPage.getByRole('alert').waitFor({state:'visible'});await localPage.getByRole('button',{name:'점검 보고서 다시 읽기',exact:true}).click();await localPage.getByRole('heading',{name:'개발센터가 점검하고, 시정하고, 다시 검사합니다.',exact:true}).waitFor({state:'visible'});assert.equal(calls,2);}finally{await localContext.close()}}});
 await check('RUNTIME','No uncaught errors during exercised flows',async()=>assert.deepEqual(errors,[]));
 const trace=path.join(root,'reviews/expansion-browser-trace.zip');await context.tracing.stop({path:trace});await browser.close();
 const stable=before===sourceDigest()&&app===sha(fs.readFileSync(path.join(root,'portal/static/app.js')));
 fs.writeFileSync(path.join(root,'quality/acceptance-browser.json'),JSON.stringify({capturedAt:new Date().toISOString(),verifier:'Codex automated Playwright/Chromium',runner:'scripts/verify-browser.cjs',url,sourceDigest:before,appSha256:app,stable,trace:{path:'reviews/expansion-browser-trace.zip',sha256:sha(fs.readFileSync(trace))},checks},null,2));if(!stable||Object.values(checks).some(c=>c.status==='FAIL'))process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{await activeBrowser?.close()});
