import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { deriveActions, validateDevelopmentForm } from '../scripts/validate-development-form.mjs';

const example = JSON.parse(await readFile(new URL('../examples/development-form.json', import.meta.url)));
const clone = value => structuredClone(value);
const codes = (form, now) => validateDevelopmentForm(form, now).map(error => error.code);

test('draft example is semantically valid', () => assert.deepEqual(validateDevelopmentForm(example), []));
test('ready requires decisions resolved and sources revisioned', () => { const f=clone(example); f.request.stage='READY'; f.request.decisions_required=['choose']; assert.ok(codes(f).includes('READY_NEEDS_DECISIONS')); assert.ok(codes(f).includes('READY_SOURCE_NOT_REVISIONED')); });
test('verification pass requires revision checks and criterion evidence', () => { const f=clone(example); f.verification.status='PASS'; const c=codes(f); assert.ok(c.includes('VERIFICATION_REVISION_REQUIRED')); assert.ok(c.includes('VERIFICATION_PASS_CHECK_REQUIRED')); assert.ok(c.includes('CRITERION_NOT_PROVEN')); });
test('schema rejects missing sections, unknown fields and invalid actors', () => { const f=clone(example); delete f.scope; f.extra=true; f.lane.actor='ATTACKER'; assert.ok(codes(f).some(code => code.startsWith('SCHEMA_'))); });
test('review requires independent actor and revision-bound receipt', () => { const f=clone(example); f.review={status:'PASSED',subject_revision:null,reviewers:['CODEX'],receipts:[],findings:[]}; const c=codes(f); assert.ok(c.includes('INDEPENDENT_REVIEW_REQUIRED')); assert.ok(c.includes('REVIEW_PROOF_REQUIRED')); });
test('granted authorization requires proof and scope', () => { const f=clone(example); f.authorization.status='GRANTED'; assert.ok(codes(f).includes('AUTHORIZATION_PROOF_REQUIRED')); });
test('release requires exact verified revision and approval', () => { const f=clone(example); f.authorization={...f.authorization,required:true,status:'PENDING'}; f.release={state:'DEPLOYED',target:'prod',revision:'a'.repeat(40),released_at:'2026-09-14T01:00:00Z',rollback:'revert'}; const c=codes(f); assert.ok(c.includes('RELEASE_REVISION_NOT_VERIFIED')); assert.ok(c.includes('RELEASE_NOT_AUTHORIZED')); });
test('success requires released target observation', () => { const f=clone(example); f.outcome.status='SUCCESS'; const c=codes(f); assert.ok(c.includes('SUCCESS_WITHOUT_RELEASE')); assert.ok(c.includes('SUCCESS_OBSERVATION_REQUIRED')); });
test('closed work cannot retain failed criteria', () => { const f=clone(example); f.request.stage='CLOSED'; f.acceptance_criteria[0].status='FAIL'; assert.ok(codes(f).includes('CLOSED_WITH_OPEN_CRITERIA')); });
test('criterion evidence must resolve to passing evidence at subject revision', () => { const f=clone(example); const rev='a'.repeat(40); f.verification={status:'PASS',subject_revision:rev,checks:[{id:'CHECK-1',kind:'TEST',status:'PASS',ref:'test',revision:'b'.repeat(40),target:null,observed_at:null}],artifacts:[]}; f.acceptance_criteria[0]={...f.acceptance_criteria[0],status:'PASS',evidence_refs:['CHECK-1']}; assert.ok(codes(f).includes('CRITERION_NOT_PROVEN')); });
test('deployed work requires review and authorization bound to target revision', () => { const f=clone(example); const rev='a'.repeat(40); f.verification={status:'PASS',subject_revision:rev,checks:[{id:'CHECK-1',kind:'TEST',status:'PASS',ref:'test',revision:rev,target:null,observed_at:null}],artifacts:[]}; f.acceptance_criteria[0]={...f.acceptance_criteria[0],status:'PASS',evidence_refs:['CHECK-1']}; f.release={state:'DEPLOYED',target:'prod',revision:rev,released_at:'2026-09-14T01:00:00Z',rollback:'revert'}; f.authorization={required:true,status:'GRANTED',action:'DEPLOY',target:'other',revision:rev,scope:['deploy'],authorized_by:{kind:'HUMAN',id:'owner',authority_ref:'decision-1'},authorized_at:'2026-09-14T00:00:00Z',expires_at:'2026-09-15T00:00:00Z'}; const c=codes(f,new Date('2026-09-14T00:30:00Z')); assert.ok(c.includes('RELEASE_NOT_REVIEWED')); assert.ok(c.includes('RELEASE_AUTHORIZATION_SCOPE_MISMATCH')); });
test('success observation is bound to released revision and target', () => { const f=clone(example); f.outcome={status:'SUCCESS',observations:[{id:'OBS-1',kind:'OBSERVATION',status:'PASS',ref:'smoke',revision:'a'.repeat(40),target:'other',observed_at:'2026-09-14T00:00:00Z'}]}; assert.ok(codes(f).includes('SUCCESS_OBSERVATION_REQUIRED')); });
test('actions expose deterministic disabled reasons', () => { const actions=deriveActions(example); assert.deepEqual(actions.mark_ready,{enabled:false,reasons:['SOURCES']}); assert.deepEqual(actions.start_isolated_work,{enabled:false,reasons:['REQUEST_NOT_READY']}); assert.deepEqual(actions.close,{enabled:false,reasons:['COMPLETION_EVIDENCE_REQUIRED']}); });
test('expired human authorization is rejected at evaluation time', () => { const f=clone(example); const rev='a'.repeat(40); f.authorization={required:true,status:'GRANTED',action:'DEPLOY',target:'prod',revision:rev,scope:['deploy'],authorized_by:{kind:'HUMAN',id:'owner',authority_ref:'decision-1'},authorized_at:'2026-09-14T00:00:00Z',expires_at:'2026-09-14T01:00:00Z'}; assert.ok(codes(f,new Date('2026-09-14T02:00:00Z')).includes('AUTHORIZATION_EXPIRED')); });
test('merge or deploy is enabled before transition only when every gate passes', () => { const f=clone(example); const rev='a'.repeat(40); f.acceptance_criteria[0]={...f.acceptance_criteria[0],status:'PASS',evidence_refs:['CHECK-1']}; f.verification={status:'PASS',subject_revision:rev,checks:[{id:'CHECK-1',kind:'TEST',status:'PASS',ref:'test',revision:rev,target:null,observed_at:null}],artifacts:[]}; f.review={status:'PASSED',subject_revision:rev,reviewers:['GEMINI'],receipts:[{id:'R-1',reviewer:'GEMINI',issuer:'gemini-cli',subject_revision:rev,verdict:'PASS',reviewed_at:'2026-09-14T00:00:00Z',ref:'review.json',artifact_digest:`sha256:${'b'.repeat(64)}`}],findings:[]}; f.release={state:'READY',target:'staging',revision:rev,released_at:null,rollback:'revert'}; assert.deepEqual(deriveActions(f).merge_or_deploy,{enabled:true,reasons:[]}); });
test('safe commit requires configured checks and selected exact paths', () => { const f=clone(example); f.request.stage='IN_PROGRESS'; assert.deepEqual(deriveActions(f).safe_commit_push.reasons,['CHECKS_NOT_CONFIGURED','PATHS_NOT_SELECTED']); assert.equal(deriveActions(f,{checksConfigured:true,selectedPaths:['src/a.js']}).safe_commit_push.enabled,true); });
