'use client';
import {useEffect,useState} from 'react';
import {Button,Input,NativeSelect} from './primitives';
import {gradeQuestions,validateLearningCatalog,type Question} from './learning-model';
import Practice from './practice';
import LearningHistory from './learning-history';
import type {WorkPlan} from './learning-model';
type Card={id:string;title:string;group:string;sources:{path:string;sha256:string}[];scope:string;explanation:string;example:{page:string;kit?:string;label:string};failureCases:string[];reuse:string;verification:{suites:string[];limitations:string};audit:{structureComplete:boolean;sourceCurrent:boolean;testsPassed:boolean;testEvidenceStatus:string;reviewComplete:boolean;approved:boolean}};
type Data={capturedAt:string;questionVersion:string;counts:{registered:number;structured:number;sourceCurrent:number;testEvidence:number;independentReviewed:number;approved:number};cards:Card[];questions:Question[];evidence:null|{capturedAt:string;current:boolean}};
export default function Academy({go}:{go:(page:string,kit?:string)=>void}){
 const [plan,setPlan]=useState<Partial<WorkPlan>>({});
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[query,setQuery]=useState(''),[group,setGroup]=useState('all'),[selected,setSelected]=useState('ssot'),[answers,setAnswers]=useState<Record<string,number>>({}),[graded,setGraded]=useState(false),[copyStatus,setCopyStatus]=useState('');
 useEffect(()=>{let alive=true;setError('');fetch('/catalog/standard-cards.json').then(r=>{if(!r.ok)throw Error('규격 카드와 검사 근거를 불러오지 못했습니다.');return r.json()}).then(async d=>{await validateLearningCatalog(d);if(alive){setAnswers({});setGraded(false);setData(d)}}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[retry]);
 if(error)return <div className="error-box" role="alert">{error}<Button onClick={()=>setRetry(n=>n+1)}>다시 불러오기</Button></div>;
 if(!data)return <p role="status">규격 카드와 검사 근거를 불러오는 중입니다.</p>;
 const cards=data.cards.filter(c=>(group==='all'||c.group===group)&&`${c.title} ${c.scope}`.toLowerCase().includes(query.toLowerCase()));const card=cards.find(c=>c.id===selected)||cards[0];const result=gradeQuestions(data.questions,answers);
 async function copy(){try{await navigator.clipboard.writeText(JSON.stringify({kind:'open_book_knowledge_check_not_certification',questionVersion:data!.questionVersion,answers,result,practiceReview:'pending'},null,2));setCopyStatus('학습 결과 복사됨')}catch{setCopyStatus('복사하지 못했습니다. 화면의 결과를 확인하세요.')}}
 return <section aria-label="규격 카드와 학습">
  <div className="mini-card"><h2>전체 자산의 의미 검수율은 미측정입니다</h2><p>아래는 등록한 12개 카드 묶음의 검사 상태입니다. 전체 수집 자산을 대표하는 검수율이 아닙니다. 센터 v1의 50개 기능 인수 조건은 별도 화면에서 확인하세요.</p><Button onClick={()=>go('acceptance')}>센터 기능 인수 현황</Button><a href="/completion.md" target="_blank" rel="noreferrer">완성도 집계 원칙 보기</a></div>
  <div className="metrics">{[['등록 카드',data.counts.registered],['필수 내용 작성',data.counts.structured],['원본 해시 일치',data.counts.sourceCurrent],['연결 검사 통과',data.counts.testEvidence],['독립 검토 완료',data.counts.independentReviewed],['정식 승인',data.counts.approved]].map(([label,n])=><div key={label}><span>{label}</span><strong>{n}<small> / {data.counts.registered}</small></strong></div>)}</div><p className="fineprint">검사·빌드 시점의 스냅샷입니다. 원본이 바뀌면 재검사·새 빌드가 필요합니다. 단계별 수치를 더하지 않으며 원본 일치는 내용 승인과 다릅니다. 검사 증거 시각 {data.evidence?.capturedAt||'없음'} · {data.evidence?.current?'검사 입력 일치':'증거 없음 또는 검사 입력 변경'}</p>
  <div className="search-row"><Input aria-label="규격 카드 검색" placeholder="규격 이름·적용 범위 검색" value={query} onChange={e=>setQuery(e.target.value)}/><NativeSelect aria-label="규격 카드 그룹" value={group} onChange={e=>setGroup(e.target.value)}><option value="all">모든 그룹</option><option value="standards">정본·재사용 원칙</option><option value="design">디자인·원자</option><option value="functions">기능</option><option value="quality">검증</option></NativeSelect></div>
  <div className="catalog-layout has-detail"><div>{cards.map(c=><button className={`doc-row ${card?.id===c.id?'active':''}`} key={c.id} onClick={()=>setSelected(c.id)}><span><strong>{c.title}</strong><code>{c.scope}</code></span><span className="life">{c.audit.testsPassed?'검사 근거 있음':'검토 필요'}</span></button>)}{!cards.length&&<div className="empty"><h3>일치하는 규격 카드가 없습니다.</h3><Button onClick={()=>{setQuery('');setGroup('all')}}>검색 초기화</Button></div>}</div>{card&&<article className="doc-detail"><h2>{card.title}</h2><h3>적용 범위</h3><p>{card.scope}</p><h3>설명</h3><p>{card.explanation}</p><h3>원본</h3>{card.sources.map(s=><div key={s.path}><code className="path">{s.path}</code><p className="fineprint">SHA {s.sha256}</p></div>)}<p>{card.audit.sourceCurrent?'고정한 원본과 해시 일치':'원본이 달라졌거나 접근 불가 · 적용 보류'}</p><h3>실행·확인 예제</h3><Button variant="outline" onClick={()=>go(card.example.page,card.example.kit)}>{card.example.label}</Button><h3>실패 사례</h3>{card.failureCases.map(s=><p key={s}>{s}</p>)}<h3>검증</h3><p>{card.verification.limitations}</p><p>연결 검사: {card.verification.suites.join(', ')||'아직 없음'} · {card.audit.testsPassed?'해당 검사 통과':'통과 증거 미확보'}</p><h3>가져다 쓰는 방법</h3><p>{card.reuse}</p><p className="note">이 카드 버전의 독립 의미 검토·정식 승인은 아직 완료되지 않았습니다.</p></article>}</div>
  <section className="mini-card learning-panel" style={{marginTop:24}}><h2>개발 판단 연습 — 10개 상황</h2><p>이해 문제이며 실무 능력 인증은 아닙니다. 모르는 문제는 비워둘 수 있습니다. 답을 고른 뒤 결과를 확인하세요.</p>{data.questions.map((q,i)=><fieldset key={q.id} style={{margin:'20px 0',padding:16}}><legend>{i+1}. {q.prompt}</legend>{q.choices.map((choice,j)=><label key={j} style={{display:'flex',gap:8,margin:'10px 0',alignItems:'flex-start'}}><input type="radio" name={q.id} checked={answers[q.id]===j} onChange={()=>{setAnswers(a=>({...a,[q.id]:j}));setGraded(false);setCopyStatus('')}}/>{choice}</label>)}{graded&&<p className="note">{result.results[i].correct?'정답':result.results[i].answered?'다시 생각해 보기':'미응답'} · {q.explanation} <Button variant="link" onClick={()=>{setGroup('all');setQuery('');setSelected(q.cardId);window.scrollTo({top:0})}}>관련 카드 보기</Button></p>}</fieldset>)}<Button onClick={()=>setGraded(true)}>학습 결과 확인</Button> <Button variant="outline" onClick={()=>{setAnswers({});setGraded(false);setCopyStatus('')}}>다시 풀기</Button>{graded&&<div role="status"><h3>정답 {result.correct} / {result.total} · 응답 {result.answered} / {result.total}</h3><p>오답·미응답의 관련 카드를 다시 확인하세요. 실제 작업 적용과 독립 검토는 별도입니다.</p><Button onClick={copy}>학습 결과 복사</Button><p>{copyStatus}</p></div>}</section>
 <Practice onPlanChange={setPlan}/><LearningHistory questions={data.questions} questionVersion={data.questionVersion} answers={answers} plan={plan}/></section>
}
