'use client';
import { useEffect, useMemo, useState } from 'react';
import StylesLibrary from './styles-library';
import SessionTour from './session-tour';
import FunctionLibrary from './function-library';
import Academy from './academy';
import Acceptance from './acceptance';
import Toolbox from './toolbox';
import DesignTools from './design-tools';
import Discovery from './discovery';
import Inspection from './inspection';
import {validateCatalogInputs} from './catalog-input';
import { Boxes, Braces, Search, ArrowUpRight, Check, Copy, Monitor, Smartphone, ShieldCheck, Layers3, GitBranch, FileCode2, AlertTriangle, ChevronRight, FolderSearch, RefreshCw } from 'lucide-react';
import { Button } from './primitives';
import { Input } from './primitives';
import { NativeSelect } from './primitives';
import { Tabs, TabsList, TabsTrigger, TabsContent } from './primitives';
import { SidebarProvider, Sidebar, SidebarContent, SidebarHeader, SidebarFooter, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarInset, SidebarTrigger } from './primitives';
import { RulesView, ConflictView, CoverageView, type Rule, type Catalog } from './evidence';
type Doc=Catalog['documents'][number];
type Source={path:string;sha256:string;source:string};
const pages=[{id:'inspection',label:'지도점검 관제실',icon:ShieldCheck},{id:'discovery',label:'몰랐던 개발 기술',icon:Braces},{id:'toolbox',label:'부품·개발 도구 모음',icon:Boxes},{id:'designTools',label:'디자인 도구 실습',icon:Braces},{id:'acceptance',label:'완성도와 검사 근거',icon:ShieldCheck},{id:'academy',label:'규격 카드·학습',icon:ShieldCheck},{id:'functions',label:'기능 창고',icon:GitBranch},{id:'tour',label:'세션 견학',icon:GitBranch},{id:'styles',label:'CSS 스타일 창고',icon:Braces},{id:'lab',label:'원자 실험실',icon:Boxes},{id:'rules',label:'만드는 규칙',icon:GitBranch},{id:'catalog',label:'전체 규격 찾기',icon:FolderSearch},{id:'conflicts',label:'충돌과 확인 과제',icon:AlertTriangle},{id:'coverage',label:'조사 범위와 근거',icon:ShieldCheck}];
const kits=[{id:'buttons',name:'버튼',symbol:'Btn · IconBtn',n:'01'},{id:'inputs',name:'입력과 드롭다운',symbol:'Input · Select',n:'02'},{id:'table',name:'표',symbol:'DataTable',n:'03'},{id:'box',name:'박스와 폼',symbol:'Section · FormCard',n:'04'},{id:'tokens',name:'디자인 토큰',symbol:'C · CTRL · FS',n:'05'}];
const examples:Record<string,string>={buttons:`import { Btn } from '@/components/ui';\n\n<Btn variant="solid" size="md" haptic={false}\n  onClick={() => setMessage('선택했습니다')}>\n  저장하기\n</Btn>`,inputs:`import { Input, Select } from '@/components/ui';\n\n<Select value={status} onChange={setStatus}\n  ariaLabel="검토 상태"\n  options={['검토 중', '확인 완료', '보류']} />`,table:`import { DataTable } from '@/components/ui';\n\n<DataTable rows={exampleRows} cols={columns}\n  onRow={(row) => setSelected(row.name)} />\n// 예시 데이터만 사용. 실제 저장 동작 없음.`,box:`import { FormCard, Input } from '@/components/ui';\n\n<FormCard title="원자 기본 정보">\n  <Input value={name} onChange={setName}\n    ariaLabel="원자 이름" full />\n</FormCard>`,tokens:`import { C, R, FS, ctrlH } from '@/components/ui';\n\n// 값은 원본 토큰에서 가져옵니다.\n// 신규 전역 치수를 선언하지 않습니다.\nconst height = ctrlH(isMobile, 'md');`};
const titles:Record<string,[string,string]>={discovery:['겉으로 보이지 않는 개발 기술을 배웁니다.','같은 문제를 다르게 해결하는 원리를 직접 비교하고, 다음 프로젝트의 질문으로 가져가세요.'],toolbox:['필요한 부품과 도구를 찾습니다.','프로젝트에 선언된 UI 부품·훅·개발 도구를 그룹과 파트로 확인하세요.'],designTools:['색과 크기, 간격을 직접 확인합니다.','값을 바꾸고 결과를 비교한 뒤 적용할 프로젝트의 원본 토큰에 연결하세요.'],acceptance:['완성도는 검사 근거로 계산합니다.','고정한 인수 조건과 전체 자산 검수 상태를 구분합니다.'],academy:['기준을 배우고, 근거로 확인합니다.','규격 카드의 실제 검사 상태와 학습 결과를 구분해서 확인하세요.'],functions:['기능도 원본과 사용처에서 시작합니다.','기존 함수·API·데이터 처리·계산·검증의 위치와 부족한 부분을 확인하세요.'],tour:['개발 전에, 여기서 기준을 맞춥니다.','이번 작업에 쓸 정본과 부품을 고르고 검증 계획을 가져가세요.'],styles:['스타일을 찾고, 원본에서 가져옵니다.','프로젝트별 CSS·변수·선택자와 동일 내용의 파일을 확인하세요.'],lab:['규격은 보고, 원자는 직접 써봅니다.','기존 코드에서 가져온 버튼·드롭다운·표·박스를 직접 조작하고 원문을 확인하세요.'],rules:['하나의 기준으로 만드는 방법.','원본 → 계약 → 원자 → 조합 → 검증. 현재 취합한 기본 작업 흐름이며, 전체 규격의 승인 완료와는 구분합니다.'],catalog:['흩어진 규격을 한곳에서.','프로젝트와 주제로 규격을 찾고 출처·행 번호·현재 버전을 확인하세요.'],conflicts:['다른 기준은 숨기지 않습니다.','문서와 구현의 차이는 승인 근거를 확인할 때까지 검토 상태로 유지합니다.'],coverage:['어디까지 확인했는지 명확하게.','코드 색인과 실제 동작 검증, 전체 규격의 승인 완료는 서로 다릅니다.']};
export default function Center(){
 const [page,setPage]=useState('inspection'),[kit,setKit]=useState('buttons'),[mobile,setMobile]=useState(false),[data,setData]=useState<Catalog|null>(null),[rules,setRules]=useState<Rule[]>([]),[sources,setSources]=useState<Record<string,Source>>({}),[error,setError]=useState(''),[query,setQuery]=useState(''),[project,setProject]=useState('all'),[category,setCategory]=useState('all'),[limit,setLimit]=useState(40),[selected,setSelected]=useState<Doc|null>(null),[copied,setCopied]=useState(false),[retry,setRetry]=useState(0);
 useEffect(()=>{let alive=true;const controller=new AbortController();setError('');Promise.all([['/catalog/index.json','규격 목록'],['/catalog/atomic-audit.json','원자 대조'],['/catalog/source-code.json','원본 코드']].map(async([path,label])=>{const r=await fetch(path,{signal:controller.signal});if(!r.ok)throw Error(`${label} 자료를 불러오지 못했습니다. 다시 시도하세요.`);try{return await r.json()}catch{throw Error(`${label} 자료의 JSON을 읽지 못했습니다. 다시 불러오세요.`)}})).then(async([c,a,s])=>{const valid=await validateCatalogInputs(c,a,s);if(alive){setData(valid.catalog);setRules(valid.rules);setSources(valid.sources)}}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false;controller.abort()}},[retry]);
 const filtered=useMemo(()=>data?.documents.filter(d=>(project==='all'||d.project===project)&&(category==='all'||d.categories.includes(category))&&`${d.title} ${d.path} ${d.rules.map(r=>r.text).join(' ')}`.toLowerCase().includes(query.toLowerCase()))||[],[data,query,project,category]);
 const current=kits.find(k=>k.id===kit)!;const src=sources[kit];const heading=page==='inspection'?['모든 개발을 규격과 증거로 지휘합니다.','프로젝트를 점검하고 시정 작업을 배정한 뒤, 새 버전에서 다시 검사해 종결합니다.']:titles[page];
 async function copy(){try{await navigator.clipboard.writeText(examples[kit]);setCopied(true);setTimeout(()=>setCopied(false),1800)}catch{setCopied(false)}}
 function go(id:string,nextKit?:string){if(nextKit)setKit(nextKit);window.scrollTo({top:0});setPage(id);setSelected(null);setQuery('');setLimit(40)}
 return <SidebarProvider style={{'--sidebar-width':'238px'} as React.CSSProperties}>
 <Sidebar className="center-sidebar"><SidebarHeader><a className="brand" href="/"><span className="brandmark"><Layers3 size={21}/></span><span>DEVCENTER<small>개발 규격 라이브러리</small></span></a></SidebarHeader><SidebarContent><div className="nav-label">WORKSPACE</div><SidebarMenu>{pages.map(p=><SidebarMenuItem key={p.id}><SidebarMenuButton isActive={page===p.id} onClick={()=>go(p.id)}><p.icon size={17}/><span>{p.label}</span>{p.id==='conflicts'&&<i className="nav-dot"/>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="sidebar-note"><ShieldCheck size={20}/><strong>SSOT FIRST</strong><p>기준을 먼저 확인하고<br/>같은 원자로 만듭니다.</p><span>기준 · 원자 · 조합 · 검증</span></div></SidebarContent><SidebarFooter><div className="footer-state"><span className="live-dot"/>출처가 연결된 현재 스냅샷</div><p className="small muted">전체 의미 검수는 진행 중</p></SidebarFooter></Sidebar>
 <SidebarInset><header className="topbar"><div><SidebarTrigger/><span className="crumb">개발센터 <ChevronRight size={13}/><b>{pages.find(p=>p.id===page)?.label}</b></span></div><div className="top-right"><span className="version">BASELINE v0.1</span><a href="https://github.com/freepass-creator/devcenter" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={14}/></a></div></header>
 <main className="workspace"><div className="page-heading"><div><div className="eyebrow">{page==='inspection'?'DEVELOPMENT GOVERNANCE':page==='lab'?'BUILD WITH THE SOURCE':'ONE REFERENCE, TRACEABLE EVIDENCE'}</div><h1>{heading[0]}</h1><p>{heading[1]}</p></div><span className="status-tag"><span/>기준 취합 · 검토 중</span></div>
 {page==='inspection'?<Inspection/>:page==='discovery'?<Discovery/>:page==='toolbox'?<Toolbox/>:page==='designTools'?<DesignTools/>:page==='acceptance'?<Acceptance/>:page==='academy'?<Academy go={go}/>:page==='tour'?<SessionTour go={go}/>:page==='functions'?<FunctionLibrary/>:error?<div className="error-box" role="alert"><AlertTriangle/>{error}<Button variant="outline" onClick={()=>setRetry(x=>x+1)}>다시 불러오기</Button></div>:!data?<div className="loading"><RefreshCw className="spin"/>출처와 규격을 불러오는 중입니다.</div>:<>
 {page!=='functions'&&<section className="metrics" aria-label="조사 요약">{[['색인한 규격 문서',data.coverage.documents,'원문 경로와 버전 연결'],['읽은 코드 파일',data.coverage.codeFilesRead,'정적 선언·참조 흔적 조사'],['직접 실행하는 원자',12,'프리패스 원본 · 예시 데이터'],['선택 원자 규격 대조',rules.length,'원문 ↔ 실제 소비 코드']].map(([a,b,c])=><div key={a}><span>{a}</span><strong>{Number(b).toLocaleString('ko-KR')}<small>{a==='선택 원자 규격 대조'?'건':'개'}</small></strong><p>{c}</p></div>)}</section>}
 {page==='lab'&&<><div className="section-heading"><div><h2>원자 실험실</h2><p>원본 파일을 빌드 시점에 읽어 만든 실행본입니다. 제품 전체의 동작 검증과는 구분합니다.</p></div><span className="source-pill"><span/>FREEPASSERP4</span></div><div className="kit-list">{kits.map(k=><Button key={k.id} variant="ghost" className={`kit ${kit===k.id?'selected':''}`} onClick={()=>{setKit(k.id);setCopied(false)}}><span>{k.n}</span><strong>{k.name}</strong><small>{k.symbol}</small></Button>)}</div>
 <section className="lab-card"><div className="lab-toolbar"><div><span className="green-dot"/><strong>{current.name}</strong><span className="muted small">원본 기반 실행본</span></div><div className="device-tabs"><Button size="sm" variant={!mobile?'secondary':'ghost'} onClick={()=>setMobile(false)} aria-pressed={!mobile}><Monitor size={15}/>데스크톱</Button><Button size="sm" variant={mobile?'secondary':'ghost'} onClick={()=>setMobile(true)} aria-pressed={mobile}><Smartphone size={15}/>모바일</Button></div></div><Tabs defaultValue="preview" className="lab-tabs"><TabsList variant="line"><TabsTrigger value="preview">미리보기</TabsTrigger><TabsTrigger value="usage">사용 코드</TabsTrigger><TabsTrigger value="source">원본 코드</TabsTrigger></TabsList><TabsContent value="preview"><div className={`preview-stage ${mobile?'mobile-mode':''}`}><iframe title={`${current.name} 원본 실행`} key={`${kit}-${mobile}`} src={`/specimen/index.html?kind=${kit}`} style={{width:mobile?'390px':'100%',height:kit==='buttons'?740:kit==='table'?440:380}}/></div></TabsContent><TabsContent value="usage"><div className="code-toolbar"><span>프로젝트 내부 사용 예제</span><Button size="sm" variant="outline" onClick={copy}>{copied?<Check size={14}/>:<Copy size={14}/>} {copied?'복사됨':'코드 복사'}</Button></div><pre className="code-block">{examples[kit]}</pre><p className="code-note">@/ 별칭과 의존성이 연결된 해당 프로젝트에서 사용합니다. 다른 프로젝트로의 패키지화는 별도 작업입니다.</p></TabsContent><TabsContent value="source"><div className="code-toolbar"><span>{src?.path}</span><span>SHA {src?.sha256.slice(0,12)}</span></div><pre className="code-block full-source">{src?.source}</pre></TabsContent></Tabs><footer className="source-footer"><FileCode2 size={15}/><code>{src?.path}</code><span>빌드 시점의 원본 · 해시 고정</span></footer></section>
 <div className="below-grid"><div className="mini-card"><span className="mini-icon"><Braces/></span><h3>원자가 만들어지는 방법</h3><p>입력과 상태를 정하고, 토큰을 사용해 원자를 만들고, 페이지에서는 조합합니다.</p><Button variant="link" onClick={()=>go('rules')}>원자 설계 규칙 보기 <ArrowUpRight size={14}/></Button></div><div className="mini-card"><span className="mini-icon amber"><AlertTriangle/></span><h3>규격 차이도 함께 확인</h3><p>표의 클릭 동작과 주석, 화면별 치수 차이를 하나의 값으로 덮지 않습니다.</p><Button variant="link" onClick={()=>go('conflicts')}>충돌과 근거 보기 <ArrowUpRight size={14}/></Button></div></div><p className="fineprint">예시 입력은 이 화면에서만 유지됩니다. 저장·API 호출은 없으며 전체 프로젝트의 동작 합격을 의미하지 않습니다. 원본 글꼴이 없으면 대체 글꼴이 보일 수 있습니다.</p></>}
 {page==='styles'&&<StylesLibrary/>}{page==='rules'&&<RulesView rules={rules}/>}{page==='conflicts'&&<ConflictView rules={rules}/>}{page==='coverage'&&<CoverageView data={data} rules={rules}/>}
 {page==='catalog'&&<><div className="search-row"><div className="search-field"><Search size={17}/><Input aria-label="규격 검색" placeholder="규격, 원자, 버튼, 프로젝트 검색" value={query} onChange={e=>{setQuery(e.target.value);setLimit(40)}}/></div><NativeSelect aria-label="프로젝트 필터" value={project} onChange={e=>{setProject(e.target.value);setLimit(40)}}><option value="all">모든 프로젝트</option>{data.projects.filter(p=>p.documents).map(p=><option key={p.name} value={p.name}>{p.name}</option>)}</NativeSelect><NativeSelect aria-label="규격 분류" value={category} onChange={e=>{setCategory(e.target.value);setLimit(40)}}><option value="all">모든 규격</option><option value="ssot">SSOT</option><option value="design">디자인</option><option value="atoms">원자</option><option value="workflow">작업·협업</option><option value="quality">검증</option></NativeSelect></div><div className="result-line"><span><b>{filtered.length.toLocaleString()}</b>개 문서</span><span>색인 결과 · 정본 확정 목록과 구분</span></div><div className={`catalog-layout ${selected?'has-detail':''}`}><div>{!filtered.length?<div className="empty"><Search/><h3>일치하는 규격이 없습니다.</h3><p>다른 단어를 입력하거나 필터를 해제하세요.</p><Button variant="outline" onClick={()=>{setQuery('');setProject('all');setCategory('all')}}>필터 해제</Button></div>:filtered.slice(0,limit).map(d=><button key={d.id} className={`doc-row ${selected?.id===d.id?'active':''}`} onClick={()=>setSelected(d)}><FileCode2 size={20}/><span><strong>{d.title}</strong><code>{d.path}</code></span><span className={`life ${d.lifecycle}`}>{d.lifecycle==='active'?'현역 목록':d.lifecycle==='archived'?'보관':'미확정'}</span><ChevronRight size={16}/></button>)}{filtered.length>limit&&<Button className="load-more" variant="outline" onClick={()=>setLimit(x=>x+40)}>40개 더 보기 ({limit}/{filtered.length})</Button>}</div>{selected&&<aside className="doc-detail"><div className="detail-top"><span className="eyebrow">SOURCE INSPECTOR</span><Button size="sm" variant="ghost" onClick={()=>setSelected(null)}>닫기</Button></div><h3>{selected.title}</h3><code className="path">{selected.path}</code><div className="detail-meta"><span>{selected.lineCount}행</span><span>SHA {selected.sha256.slice(0,12)}</span></div><h4>원문에서 발견한 규칙</h4>{selected.rules.map((r,i)=><div className="excerpt" key={i}><b>L{r.line}</b><p>{r.text}</p></div>)}{!selected.rules.length&&<p>명시적 규칙 문장을 추출하지 못했습니다. 원문 확인이 필요합니다.</p>}<p className="fineprint">관련 문장 최대 10개를 표시합니다. 자동 추출이며 승인/현행 의미는 개별 검토가 필요합니다.</p></aside>}</div></>}
 </>}
 <footer className="workspace-footer"><span>DEVCENTER / 규격과 원자</span><span>원본을 보존하고, 사용과 검증을 연결합니다.</span></footer></main></SidebarInset></SidebarProvider>
}
