'use client';
import {useState} from 'react';
import {Button,Input,NativeSelect} from './primitives';
import {contrast,dimension,gridRecipe} from './design-tools-model';
export default function DesignTools(){const [fg,setFg]=useState('#1f2937'),[bg,setBg]=useState('#ffffff'),[columns,setColumns]=useState('3'),[gap,setGap]=useState('16'),[px,setPx]=useState('16'),[base,setBase]=useState('16'),[copied,setCopied]=useState('');
 let colors:ReturnType<typeof contrast>|null=null,colorError='',grid='',gridError='',rem='',unitError='';try{colors=contrast(fg,bg)}catch(e){colorError=(e as Error).message}try{grid=gridRecipe(dimension(columns,1,6),dimension(gap,0,64))}catch(e){gridError=(e as Error).message}try{rem=(dimension(px,0,1024)/dimension(base,1,100)).toFixed(4).replace(/\.?0+$/,'')||'0'}catch(e){unitError=(e as Error).message}
 return <section aria-label="디자인 도구 실습"><p className="note">직접 값을 바꾸며 확인하는 실험 도구입니다. 생성 값은 신규 공통 규격이 아니며, 실제 사용 시 해당 프로젝트의 원본 토큰을 적용합니다.</p><div className="tool-grid">
 <article className="mini-card"><h2>글자와 배경 대비</h2><label>글자색<Input aria-label="대비 글자색" value={fg} onChange={e=>setFg(e.target.value)}/></label><label>배경색<Input aria-label="대비 배경색" value={bg} onChange={e=>setBg(e.target.value)}/></label>{colorError?<p role="alert">{colorError}</p>:<><div className="design-swatch" style={{color:fg,background:bg}}>같은 글자, 읽기 편한 색<br/><strong>개발센터 123,456</strong></div><p role="status">대비 {colors!.ratio.toFixed(2)}:1 · 일반 글자 AA {colors!.normalAA?'충족':'미충족'} · 큰 글자 AA {colors!.largeAA?'충족':'미충족'}</p><p>표시값을 반올림하기 전 비율로 판정합니다. 이 계산은 페이지 전체 접근성 검사가 아닙니다.</p></>}<a href="https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html" target="_blank" rel="noreferrer">W3C 대비 기준과 큰 글자 정의</a></article>
 <article className="mini-card"><h2>px ↔ rem 환산</h2><label>픽셀<Input type="number" aria-label="환산 픽셀" value={px} onChange={e=>setPx(e.target.value)}/></label><label>기준 글자 크기<Input type="number" aria-label="환산 기준 크기" value={base} onChange={e=>setBase(e.target.value)}/></label>{unitError?<p role="alert">{unitError}</p>:<output className="design-swatch">{px}px = {rem}rem</output>}<p>rem은 루트 글자 크기에 비례합니다. 여기서는 입력한 기준값으로 계산합니다.</p></article>
 <article className="mini-card"><h2>반응형 격자와 간격</h2><label>열 개수<NativeSelect aria-label="격자 열 개수" value={columns} onChange={e=>{setColumns(e.target.value);setCopied('')}}>{[1,2,3,4,5,6].map(n=><option key={n}>{n}</option>)}</NativeSelect></label><label>간격<Input type="number" aria-label="격자 간격" value={gap} onChange={e=>{setGap(e.target.value);setCopied('')}}/></label>{gridError?<p role="alert">{gridError}</p>:<><div className="grid-tool-preview" style={{display:'grid',gridTemplateColumns:`repeat(${columns},minmax(0,1fr))`,gap:Number(gap)}}>{[1,2,3,4,5,6].map(n=><div key={n} className="grid-tool-cell">부품 {n}</div>)}</div><pre className="code-block">{grid}</pre><Button onClick={async()=>{try{await navigator.clipboard.writeText(grid);setCopied('격자 예제 복사됨')}catch{setCopied('복사 실패')}}}>격자 예제 복사</Button><p role="status">{copied}</p></>}</article>
 </div><article className="mini-card"><h2>외부 도구를 보는 기준</h2><p>도구를 설치하기 전에 현재 프로젝트가 쓰는 것을 도구 모음에서 먼저 확인하세요. 아래는 공식 설명을 확인한 탐색 후보이며, 센터에 설치하거나 통합한 도구는 아닙니다.</p><p><a href="https://storybook.js.org/docs" target="_blank" rel="noreferrer">Storybook</a> — UI 부품의 상태와 사용 예제를 분리해 확인하는 작업 환경.</p><p><a href="https://www.radix-ui.com/primitives/docs/overview/introduction" target="_blank" rel="noreferrer">Radix Primitives</a> — 동작·접근성을 고려한 UI 기본 부품. 적용 후 제품 수준의 검증은 필요합니다.</p></article></section>
}
