'use client';
import {useEffect,useState} from 'react';
import {Button,Input,NativeSelect} from './primitives';
import {emptySearch,finishSearch,saveVersion,startSearch,submitOnce,type DocumentVersion,type RequestLedger} from './discovery-model';

const expectedSourceSha='__DEVCENTER_DISCOVERY_SOURCE_SHA__';
const topics=[
 {id:'versions',group:'데이터를 지키기',title:'동시 수정 충돌',term:'낙관적 동시성 제어',scene:'두 AI가 같은 v1 문서를 읽고 각각 저장하면 앞의 수정이 사라질 수 있습니다.',question:'내가 읽은 버전과 지금 원본 버전이 같은지 확인하는가?',source:'https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/412',sourceName:'MDN · 조건부 요청과 412',live:true,gate:'실제 저장소에서 버전 비교와 저장을 하나의 원자적 연산으로 처리하고, 충돌 후 재조회·차이 검토를 시험한다.'},
 {id:'once',group:'데이터를 지키기',title:'재시도해도 한 번만',term:'멱등성 키',scene:'저장은 됐지만 응답이 끊겼습니다. 같은 요청을 다시 보낼 때 두 건이 생기면 안 됩니다.',question:'같은 요청의 표식과 내용을 함께 확인하는가?',source:'https://docs.stripe.com/api/idempotent_requests',sourceName:'Stripe · 멱등 요청 설계 사례',live:true,gate:'사용자·작업별 키 범위, 본문 비교, 원자적 중복 차단, 보관 기간, 처리 중 응답과 실패 후 재시도를 서버에서 검증한다.'},
 {id:'race',group:'화면을 믿게 만들기',title:'늦게 온 응답 다루기',term:'요청 경합 방지',scene:'새 검색 결과가 먼저 도착한 뒤 옛 응답이 늦게 오면, 화면이 이전 검색으로 돌아갈 수 있습니다.',question:'도착한 응답이 현재 사용자가 기다리는 요청인가?',source:'https://react.dev/reference/react/useEffect',sourceName:'React · Effect의 응답 경합',live:true,gate:'실제 네트워크 지연·취소·실패·화면 이탈을 재현한다. 옛 응답 무시는 서버 작업 취소와 다르다.'},
 {id:'states',group:'흐름을 설계하기',title:'불가능한 상태를 없애기',term:'상태 머신',scene:'저장 중인데 완료 버튼도 보이고 실패 메시지도 뜨는 모순을 줄입니다.',question:'준비 → 처리 중 → 성공/실패 사이에 허용된 이동이 정해져 있는가?',source:'https://stately.ai/docs/machines',sourceName:'Stately · 상태 머신',live:false,gate:'현재 기능의 상태·이벤트·허용/금지 전이를 먼저 표로 만들고, 금지 전이가 실제로 거절되는지 시험한다.'},
 {id:'properties',group:'검사 능력 키우기',title:'내가 생각 못 한 입력 찾기',term:'속성 기반 테스트',scene:'예시 3개가 맞아도 이상한 숫자·문자 조합에서 깨질 수 있습니다.',question:'어떤 입력이 오더라도 항상 지켜야 할 성질은 무엇인가?',source:'https://fast-check.dev/docs/introduction/',sourceName:'fast-check · 자동 입력과 반례 축소',live:false,gate:'업무에서 참인 성질을 원본으로 정의하고, 발생한 반례와 재현용 seed를 기록한다. 라이브러리 설치만으로 규칙이 옳아지지는 않는다.'},
 {id:'traces',group:'운영을 이해하기',title:'문제가 시작된 곳 따라가기',term:'추적·로그·지표',scene:'화면에는 저장 실패만 보여도 요청이 어느 처리 단계에서 멈췄는지 찾아야 합니다.',question:'같은 요청을 화면·API·저장소에서 연결할 수 있는가?',source:'https://opentelemetry.io/docs/concepts/signals/',sourceName:'OpenTelemetry · 관측 신호',live:false,gate:'요청 연결, 실패 경로, 수집 비용, 보관 기간을 확인한다. 고객정보·비밀 값이 로그에 섞이지 않는지 검사한다.'},
 {id:'flags',group:'운영을 이해하기',title:'새 기능을 조금씩 켜기',term:'기능 플래그',scene:'모든 사용자에게 한 번에 새 화면을 켜기 전에 일부 범위에서 확인합니다.',question:'누구에게 켜져 있고 문제가 생기면 어떻게 끄는가?',source:'https://openfeature.dev/docs/reference/intro/',sourceName:'OpenFeature · 기능 플래그 API',live:false,gate:'기본값·대상 범위·평가 실패·종료 시 제거를 정한다. 플래그 끄기는 데이터 변경의 롤백이 아니다.'},
 {id:'visual',group:'검사 능력 키우기',title:'모르게 바뀐 화면 잡기',term:'시각적 회귀 검사',scene:'버튼 CSS 하나를 바꿨는데 다른 화면의 표와 줄바꿈이 틀어질 수 있습니다.',question:'승인된 기준 화면과 실제 화면의 차이를 검토하는가?',source:'https://playwright.dev/docs/test-snapshots',sourceName:'Playwright · 화면 비교',live:false,gate:'같은 브라우저·글꼴·크기·데이터로 비교하고 기준 이미지는 사람이 검토한다. 스크린샷 한 장은 회귀 검사가 아니다.'},
 {id:'keyboard',group:'화면을 믿게 만들기',title:'마우스 없이 끝까지 쓰기',term:'키보드 접근성과 초점',scene:'예쁜 메뉴도 Tab으로 갈 수 없거나 닫은 뒤 초점을 잃으면 쓰기 어렵습니다.',question:'Tab·Enter·Escape로 핵심 작업을 끝낼 수 있는가?',source:'https://www.w3.org/WAI/WCAG22/Understanding/keyboard.html',sourceName:'W3C · 키보드 접근',live:false,gate:'실제 사용자 흐름의 초점 순서·표시·복귀와 대화상자 이탈을 직접 검사한다. 이 링크 열람은 접근성 합격이 아니다.'},
];
function VersionLab(){const initial=()=>({protect:true,doc:{value:'기본 제목',version:1} as DocumentVersion,a:'AI A의 제목',b:'AI B의 제목',base:{a:1,b:1},message:'두 편집자가 같은 v1을 읽었습니다.'});const [view,setView]=useState(initial);const {protect,doc,a,b,base,message}=view;
 const setA=(a:string)=>setView(v=>({...v,a})),setB=(b:string)=>setView(v=>({...v,b}));
 function save(who:'a'|'b'){setView(v=>{try{const r=saveVersion(v.doc,v.base[who],v[who],v.protect);return {...v,doc:r.document,base:r.status==='saved'?{...v.base,[who]:r.document.version}:v.base,message:r.status==='conflict'?'충돌 차단: 원본을 다시 읽고 두 변경의 차이를 검토하세요.':`${who.toUpperCase()} 저장됨 · 원본 v${r.document.version}`}}catch(e){return {...v,message:(e as Error).message}}})}

 return <><label className="check-label"><input type="checkbox" checked={protect} onChange={e=>{const checked=e.target.checked;setView({...initial(),protect:checked})}}/> 버전 검사 켜기</label><p>① A 저장 → ② B 저장. 검사를 끄고 초기화한 뒤 같은 순서를 비교하세요.</p><div className="discovery-columns">{(['a','b'] as const).map(who=><div key={who}><label><span id={`version-${who}`}>AI {who.toUpperCase()} · 읽은 버전 v{base[who]}</span><Input aria-label={`AI ${who.toUpperCase()} 수정 내용`} aria-describedby={`version-${who}`} maxLength={120} value={who==='a'?a:b} onChange={e=>who==='a'?setA(e.target.value):setB(e.target.value)}/></label><Button onClick={()=>save(who)}>{who.toUpperCase()} 저장</Button><Button variant="outline" onClick={()=>{setView(v=>({...v,base:{...v.base,[who]:v.doc.version},message:'최신 원본을 읽고 내 초안을 보존했습니다. 원본과 비교한 뒤 병합 내용을 입력하세요.'}))}}>{who.toUpperCase()} 원본 다시 읽기</Button></div>)}</div><output className="spec-output" aria-label="동시 수정 원본">원본 v{doc.version} · {doc.value}</output><p role="status">{message}</p><Button variant="outline" onClick={()=>{setView(v=>({...initial(),protect:v.protect}))}}>동시 수정 초기화</Button><p className="note">서버 없이 메모리에서 순서를 재현합니다. 실제 저장소의 원자성·권한·네트워크 검증을 대신하지 않습니다. 원본 다시 읽기는 내 초안을 보존합니다. 화면의 원본과 비교 후 병합 내용을 직접 입력하세요. 보호 모드를 바꾸면 실험이 초기화됩니다.</p></>;
}
function OnceLab(){const [view,setView]=useState({protect:true,ledger:{rows:[]} as RequestLedger,key:'request-001',payload:'예시 메모',message:'같은 요청을 두 번 보내 보세요.'});const {protect,ledger,key,payload,message}=view;const setKey=(key:string)=>setView(v=>({...v,key})),setPayload=(payload:string)=>setView(v=>({...v,payload}));return <><label className="check-label"><input type="checkbox" checked={protect} onChange={e=>{const protect=e.target.checked;setView(v=>({...v,protect,ledger:{rows:[]},message:'보호 모드를 바꾸어 실험 기록을 초기화했습니다.'}))}}/> 중복 요청 검사 켜기</label><p>① 같은 내용으로 두 번 전송 → ② 같은 표식으로 내용만 바꿔 전송. 보호 설정을 비교할 때는 초기화부터 하세요.</p><label>같은 작업을 알아보는 표식<Input aria-label="실험 요청 표식" maxLength={80} value={key} onChange={e=>setKey(e.target.value)}/></label><label>저장할 내용<Input aria-label="실험 요청 내용" maxLength={120} value={payload} onChange={e=>setPayload(e.target.value)}/></label><Button onClick={()=>{setView(v=>{try{const r=submitOnce(v.ledger,v.key,v.payload,v.protect);return {...v,ledger:r.ledger,message:r.status==='created'?`새 기록 생성 · ${r.result}`:r.status==='replayed'?`기존 결과 재사용 · ${r.result}`:'같은 표식인데 내용이 다릅니다 · 요청 충돌'}}catch(e){return {...v,message:(e as Error).message}}})}}>같은 저장 요청 보내기</Button><output className="spec-output" aria-label="중복 요청 기록 수">생성된 기록 {ledger.rows.length}건</output><p role="status">{message}</p><ol>{ledger.rows.map(r=><li key={r.result}>{r.result} · {r.payload}</li>)}</ol><Button variant="outline" onClick={()=>{setView(v=>({...v,ledger:{rows:[]},message:'이 실험의 기록을 초기화했습니다.'}))}}>중복 요청 초기화</Button><p className="note">브라우저 메모리의 순차 호출 실험입니다. 서버 동시 요청·키 보관·실패 복구는 구현하지 않았습니다. 키는 공백·대소문자까지 정확히 같아야 같은 작업입니다. 키를 임의로 정규화하지 않습니다. 보호 모드를 바꾸면 기록이 초기화됩니다.</p></>}
function RaceLab(){const [view,setView]=useState({protect:true,state:emptySearch(),query:'첫 검색',message:'요청 두 개를 만든 뒤 두 번째 응답을 먼저 도착시키세요.'});const {protect,state,query,message}=view;const setQuery=(query:string)=>setView(v=>({...v,query}));return <><label className="check-label"><input type="checkbox" checked={protect} onChange={e=>{const protect=e.target.checked;setView(v=>({...v,protect,state:emptySearch(),message:'보호 모드를 바꾸어 대기 요청을 초기화했습니다.'}))}}/> 최신 요청 응답만 반영</label><p>① 서로 다른 검색 두 개 요청 → ② 2번 응답 → ③ 1번 응답 도착. 보호를 끄고 초기화한 뒤 비교하세요.</p><label>검색어<Input aria-label="응답 실험 검색어" maxLength={80} value={query} onChange={e=>setQuery(e.target.value)}/></label><Button onClick={()=>{setView(v=>{try{return {...v,state:startSearch(v.state,v.query),message:'응답 대기 목록에 추가했습니다. 도착 순서를 직접 고르세요.'}}catch(e){return {...v,message:(e as Error).message}}})}}>검색 요청 만들기</Button><p>최신 요청 번호 {state.latest||'없음'}</p><div className="discovery-pending">{state.pending.map(r=><Button variant="outline" key={r.id} onClick={()=>{setView(v=>{try{const result=finishSearch(v.state,r.id,v.protect);return {...v,state:result.state,message:result.ignored?'늦게 온 옛 응답 무시':'도착한 응답을 화면에 반영'}}catch(e){return {...v,message:(e as Error).message}}})}}>{r.id}번 응답 도착 · {r.query}</Button>)}</div><output className="spec-output" aria-label="현재 검색 결과">화면 결과 · {state.visible}</output><p role="status">{message}</p><Button variant="outline" onClick={()=>{setView(v=>({...v,state:emptySearch(),message:'응답 실험을 초기화했습니다.'}))}}>응답 실험 초기화</Button><p className="note">응답 순서를 수동으로 재현하는 모델입니다. 실제 HTTP 요청·취소·타임아웃은 수행하지 않습니다. 보호 모드를 바꾸면 대기 요청이 초기화됩니다.</p></>}
export default function Discovery(){const [group,setGroup]=useState('all'),[query,setQuery]=useState(''),[selected,setSelected]=useState('versions'),[copied,setCopied]=useState(''),[source,setSource]=useState<{path:string;sha256:string;source:string}|null>(null),[sourceError,setSourceError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{const controller=new AbortController();setSourceError('');fetch('/catalog/discovery-source.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error('실험 원본을 읽지 못했습니다.');return r.json()}).then(async d=>{if(typeof d.path!=='string'||typeof d.source!=='string'||typeof d.sha256!=='string')throw Error('실험 원본 형식 오류');if(!globalThis.crypto?.subtle)throw Error('코드 버전 확인에는 HTTPS 또는 localhost 접속이 필요합니다.');const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(d.source))),b=>b.toString(16).padStart(2,'0')).join('');if(hash!==d.sha256||hash!==expectedSourceSha)throw Error('실험 원본 해시 불일치');if(!controller.signal.aborted)setSource(d)}).catch(e=>{if(!controller.signal.aborted)setSourceError(e.message)});return()=>controller.abort()},[retry]);
 const filtered=topics.filter(t=>(group==='all'||t.group===group)&&`${t.title} ${t.term} ${t.scene} ${t.question} ${t.sourceName} ${t.group}`.toLowerCase().includes(query.trim().toLowerCase())),topic=filtered.find(t=>t.id===selected)||filtered[0];
 return <section className="discovery" aria-label="몰랐던 개발 기술"><p className="note">이미 쓰고 있다는 뜻이 아닙니다. 3개는 실행 모델, 6개는 공식 자료를 연결한 학습 안내입니다. 새 도구를 설치하거나 공통 규격으로 승인하지 않았습니다.</p><div className="search-row"><Input aria-label="새 기술 검색" placeholder="겪는 문제나 기술 이름" value={query} onChange={e=>setQuery(e.target.value)}/><NativeSelect aria-label="새 기술 그룹" value={group} onChange={e=>setGroup(e.target.value)}><option value="all">모든 그룹</option>{[...new Set(topics.map(t=>t.group))].map(g=><option key={g}>{g}</option>)}</NativeSelect></div><div className="discovery-layout"><nav aria-label="새 기술 목록">{filtered.map(t=><button key={t.id} className={`doc-row ${t.id===topic?.id?'active':''}`} aria-pressed={t.id===topic?.id} onClick={()=>{setSelected(t.id);setCopied('')}}><span><strong>{t.title}</strong><span>{t.group} · {t.live?'직접 실험':'학습 안내'}</span></span></button>)}{!filtered.length&&<div className="empty"><p>일치하는 새 기술이 없습니다.</p><Button onClick={()=>{setGroup('all');setQuery('')}}>새 기술 필터 초기화</Button></div>}</nav>{topic?<article className="mini-card learning-panel"><p className="eyebrow">{topic.group} / {topic.live?'실행 모델':'학습 안내'}</p><h2>{topic.title}</h2><p><strong>{topic.term}</strong> · {topic.scene}</p><p className="note">개발자에게 물을 질문: {topic.question}</p>{topic.id==='versions'?<VersionLab/>:topic.id==='once'?<OnceLab/>:topic.id==='race'?<RaceLab/>:<p className="spec-output">이 파트는 아직 실행 실험이 없습니다. 아래 원문과 적용 계획으로 다음 작업을 준비하세요.</p>}<h3>실제 프로젝트에 적용할 때</h3><p>{topic.gate}</p><a href={topic.source} target="_blank" rel="noreferrer">{topic.sourceName}</a><p><Button onClick={async()=>{try{await navigator.clipboard.writeText(JSON.stringify({kind:'learning_candidate_not_approved',topic:topic.title,concept:topic.term,officialSource:topic.source,question:topic.question,verification:topic.gate,project:'작성 필요',sourceVersion:'원본 확인 필요',approved:false},null,2));setCopied('적용 질문과 검증 계획 복사됨')}catch{setCopied('복사 실패 · 화면의 질문과 검증 계획을 직접 선택하세요.')}}}>AI에게 줄 적용 계획 복사</Button></p><p role="status">{copied}</p></article>:<p className="mini-card learning-panel">검색을 초기화하면 실험을 다시 선택할 수 있습니다.</p>}</div><details className="mini-card learning-panel"><summary>세 실험의 실제 코드와 출처</summary><p>센터가 만든 학습용 후보 코드의 빌드 시점 사본입니다. 현재 실행 묶음에 고정한 해시와 대조합니다. 원본의 현행 승인이나 서버 위변조 방지를 보증하지 않습니다. 화면과 단위 검사가 이 모듈을 함께 사용합니다.</p>{sourceError?<><p role="alert">{sourceError}</p><Button onClick={()=>setRetry(n=>n+1)}>실험 원본 다시 읽기</Button></>:source?<><code className="path">{source.path} · SHA-256 {source.sha256}</code><pre className="code-block">{source.source}</pre></>:<p role="status">실험 원본을 읽는 중입니다.</p>}</details></section>;
}
