import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const here=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),root=here;
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const catalogFile=path.join(here,'src/learning/cards.json'),catalogBytes=fs.readFileSync(catalogFile),catalog=JSON.parse(catalogBytes),evidenceFile=path.join(here,'test/fixtures/catalog-portal/card-evidence.json');
const suiteFiles={button:'test/catalog-portal/verify-button-recipes.cjs',examples:'test/catalog/verify-function-examples.mjs',gate:'test/verification/verify-typecheck-gate.mjs',collector:'test/catalog/verify-function-collector.mjs'};
// Evidence depends on the original inputs and validation implementation, not just a PASS label.
const manifestArg=process.argv.indexOf('--manifest'),manifestFile=manifestArg<0?path.join(here,'src/catalog-portal/static/source-manifest.json'):path.resolve(process.argv[manifestArg+1]);
function inputs(){const paths=new Set([catalogFile,...catalog.cards.flatMap(c=>c.sources.map(s=>path.resolve(root,s.path))),...Object.values(suiteFiles).map(p=>path.join(here,p)),...['scripts/catalog/card-audit.mjs','scripts/verification/typecheck-gate.mjs','scripts/catalog/function-python-index.py','scripts/catalog-portal/build-static.mjs','src/catalog-portal/app/specimen/page.tsx','src/catalog-portal/tsconfig.json','src/catalog-portal/tsconfig.gallery.json'].map(p=>path.join(here,p))]);for(const file of fs.readdirSync(path.join(here,'src/catalog-portal/app')))if(/\.tsx?$/.test(file))paths.add(path.join(here,'src/catalog-portal/app',file));const manifest=JSON.parse(fs.readFileSync(manifestFile,'utf8'));const regular=[...new Set([...paths].map(p=>path.resolve(p)))].sort().map(p=>({path:p.replaceAll('\\','/'),sha256:fs.existsSync(p)?sha(fs.readFileSync(p)):null}));return [...regular,...manifest.sources.map(s=>({path:s.path,sha256:s.sha256}))]}
const digest=x=>sha(JSON.stringify(x));
if(process.argv.includes('--verify')){const before=inputs(),suites={};for(const [id,file] of Object.entries(suiteFiles)){const r=spawnSync(process.execPath,[path.join(here,file)],{cwd:here,encoding:'utf8',timeout:120000,windowsHide:true,maxBuffer:2*1024*1024});suites[id]={passed:r.status===0,exitCode:r.status,summary:r.status===0?r.stdout.trim():'검사 실패 또는 시간 초과',outputHash:sha((r.stdout||'')+(r.stderr||''))};console.log(id,r.status===0?'PASS':'FAIL')};const after=inputs(),stable=digest(before)===digest(after);fs.writeFileSync(evidenceFile,JSON.stringify({capturedAt:new Date().toISOString(),catalogSha256:sha(catalogBytes),inputs:before,inputDigest:digest(before),stable,suites},null,2));if(!stable||Object.values(suites).some(s=>!s.passed))process.exitCode=1;}
const evidence=fs.existsSync(evidenceFile)?JSON.parse(fs.readFileSync(evidenceFile,'utf8')):null;
const evidenceCurrent=!!evidence&&evidence.stable&&evidence.catalogSha256===sha(catalogBytes)&&evidence.inputDigest===digest(inputs());
const seen=new Set();const cards=catalog.cards.map(c=>{if(seen.has(c.id))throw Error('Duplicate card id');seen.add(c.id);for(const s of c.sources){const p=path.resolve(root,s.path);if(!p.startsWith(root+path.sep))throw Error('Source outside project root')};const sourceCurrent=c.sources.length>0&&c.sources.every(s=>{const p=path.resolve(root,s.path);return fs.existsSync(p)&&sha(fs.readFileSync(p))===s.sha256});const complete=!!(c.scope?.trim()&&c.explanation?.trim()&&c.example?.page&&c.failureCases?.length&&c.reuse?.trim()&&c.verification?.limitations?.trim()&&c.sources.length);const knownSuites=c.verification.suites.every(id=>Object.hasOwn(suiteFiles,id));const tested=knownSuites&&evidenceCurrent&&sourceCurrent&&c.verification.suites.length>0&&c.verification.suites.every(id=>evidence.suites[id]?.passed);return {...c,audit:{structureComplete:complete,sourceCurrent,testsPassed:tested,testEvidenceStatus:!c.verification.suites.length?'not_linked':!evidenceCurrent?'missing_or_stale':tested?'passed':'failed',reviewComplete:false,approved:false}}});
for(const q of catalog.questions)if(!seen.has(q.cardId))throw Error('Question refers to missing card');
const report={kind:'card_status_not_overall_completion',capturedAt:new Date().toISOString(),overallPercentage:null,denominatorStatus:'asset_coverage_unmeasured_platform_report_separate',questionVersion:sha(JSON.stringify(catalog.questions)),counts:{registered:cards.length,structured:cards.filter(c=>c.audit.structureComplete).length,sourceCurrent:cards.filter(c=>c.audit.sourceCurrent).length,testEvidence:cards.filter(c=>c.audit.testsPassed).length,independentReviewed:0,approved:0},evidence:evidence?{capturedAt:evidence.capturedAt,current:evidenceCurrent,suites:evidence.suites}:null,cards,questions:catalog.questions};
const arg=process.argv.indexOf('--report');if(arg>=0)fs.writeFileSync(path.resolve(process.argv[arg+1]),JSON.stringify(report));else console.log(JSON.stringify(report.counts));
