'use client';
import { useEffect, useState } from 'react';
import ButtonGallery from '../button-gallery';
import { Check, Plus } from 'lucide-react';
import { Btn, IconBtn } from '@fp4/components/ui/buttons';
import { Input, Select, Checkbox, Textarea, SearchInput } from '@fp4/components/ui/form-controls';
import { DataTable } from '@fp4/components/ui/table';
import { Section, FormCard } from '@fp4/components/ui/detail';
import { C, R, CTRL, FS } from '@fp4/components/ui/tokens';
import '@fp4/app/globals.css';

const rows=[{name:'Btn',kind:'버튼',source:'buttons.tsx',state:'원본 실행'},{name:'Select',kind:'드롭다운',source:'form-controls.tsx',state:'원본 실행'},{name:'DataTable',kind:'표',source:'table.tsx',state:'클릭 확인'}];
export default function Specimen(){
 const [emptyTable,setEmptyTable]=useState(false);
 const [kind,setKind]=useState('buttons'),[size,setSize]=useState<'sm'|'md'|'lg'>('md'),[name,setName]=useState('공통 원자'),[choice,setChoice]=useState('검토 중'),[checked,setChecked]=useState(false),[message,setMessage]=useState('버튼을 눌러 동작을 확인하세요.'),[clicks,setClicks]=useState(0),[selected,setSelected]=useState(''),[search,setSearch]=useState('');
 useEffect(()=>{setKind(new URLSearchParams(location.search).get('kind')||'buttons')},[]);
 const note={fontSize:12,color:'#66736c',lineHeight:1.7} as const;
 return <main className="specimen" style={{padding:'28px 30px',background:'#fff',minHeight:'100vh',boxSizing:'border-box',fontFamily:'Pretendard, "Segoe UI", sans-serif',color:'#27382f'}}>
  {kind==='buttons'&&<ButtonGallery/>}
  {kind==='inputs'&&<><div className="spec-label">INPUT / SELECT / CHECKBOX</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:20,marginTop:22}}><label style={note}>이름<Input ariaLabel="원자 이름" value={name} onChange={setName} full/></label><label style={note}>검토 상태<Select ariaLabel="검토 상태" value={choice} onChange={setChoice} options={['검토 중','확인 완료','보류']} full/></label></div><div style={{margin:'16px 0'}}><SearchInput ariaLabel="예시 검색" value={search} onChange={setSearch} full/></div><Textarea ariaLabel="예시 메모" value={message==='버튼을 눌러 동작을 확인하세요.'?'':message} onChange={setMessage} placeholder="직접 입력해 보세요" full rows={2}/><label style={{display:'flex',gap:8,alignItems:'center',margin:'15px 0',fontSize:13}}><Checkbox ariaLabel="규격 확인" checked={checked} onChange={setChecked}/>규격을 확인했습니다</label><output className="spec-output" aria-live="polite">{name} · {choice} · {checked?'확인 체크됨':'체크 안 됨'}{search&&` · 검색: ${search}`}</output></>}
  {kind==='table'&&<><div className="spec-label">DATA TABLE / EXAMPLE DATA</div><label style={{display:"flex",gap:8,margin:"16px 0"}}><Checkbox ariaLabel="빈 표 보기" checked={emptyTable} onChange={setEmptyTable}/>빈 표 보기</label><DataTable rows={emptyTable?[]:rows} cols={[{key:'name',label:'원자',render:r=><strong>{r.name}</strong>},{key:'kind',label:'종류',render:r=>r.kind},{key:'source',label:'원본 파일',render:r=>r.source},{key:'state',label:'상태',render:r=>r.state}]} onRow={r=>{setSelected(r.name);setClicks(x=>x+1)}}/><output className="spec-output" style={{marginTop:20}} aria-live="polite">{emptyTable?'표시할 행이 없습니다.':selected?`${selected} 선택 · onRow ${clicks}회 호출`:'행을 클릭하거나 키보드로 선택해 보세요.'}</output><p style={{...note,marginTop:14}}>원본 주석은 더블클릭 상세라고 설명하지만, 현재 구현은 단일 클릭에서도 onRow를 호출합니다. 예시 화면에서 관찰한 결과와 문서의 차이를 비교하세요.</p></>}
  {kind==='box'&&<><div className="spec-label">SECTION / FORM CARD</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:20,marginTop:22}}><Section title="규격 요약"><div style={{padding:14,lineHeight:1.8,fontSize:13}}>원본 위치와 입력 계약을 확인합니다.<br/>표현과 업무 사실은 분리합니다.</div></Section><FormCard title="원자 기본 정보" hint="실제 저장되지 않는 예시입니다"><div style={{padding:12}}><Input ariaLabel="폼 원자 이름" value={name} onChange={setName} full/><div style={{marginTop:12}}><Btn haptic={false} onClick={()=>setMessage(`${name} 입력을 확인했습니다.`)}>입력 확인</Btn></div></div></FormCard></div><output className="spec-output" aria-live="polite" style={{marginTop:20}}>{message}</output><p style={note}>Section과 FormCard의 라운드 차이도 원본을 그대로 사용합니다.</p></>}
  {kind==='tokens'&&<><div className="spec-label">BUILD SNAPSHOT / SOURCE TOKENS</div><div style={{display:'flex',gap:16,flexWrap:'wrap',margin:'22px 0'}}>{(['head','brand','ok','warn','danger','bg','line'] as const).map(k=><div key={k}><div style={{background:C[k],width:62,height:46,border:'1px solid #dce4df',borderRadius:R}}/><code style={{fontSize:11}}>C.{k}</code></div>)}</div><table style={{fontSize:13,borderCollapse:'collapse',width:'100%'}}><thead><tr><th>CTRL</th><th>웹 높이</th><th>모바일 높이</th><th>웹 글자</th><th>모바일 글자</th></tr></thead><tbody>{Object.entries(CTRL).map(([k,v])=><tr key={k} style={{borderTop:'1px solid #e0e5e2',height:34}}><td>{k}</td><td>{v.web}</td><td>{v.mobile}</td><td>{v.fsWeb}</td><td>{v.fsMobile}</td></tr>)}</tbody></table><p style={{...note,marginTop:14}}>R = {R} · FS.body = {FS.body}. 빌드 시점 원본 토큰의 값을 표시합니다.<br/>문서와 다른 값은 승인된 글로벌 기본값이 아니라 충돌 검토 대상입니다.</p></>}
 </main>
}
