'use client';
import {useState} from 'react';
import {Check,Plus,Search,List,LayoutGrid,LoaderCircle} from 'lucide-react';
import {Btn,IconBtn,IconSeg,ButtonLabel} from '@fp4/components/ui/buttons';
import {Select,Checkbox} from '@fp4/components/ui/form-controls';
const variants=['solid','ghost','danger','bare'] as const;
const sizes=['sm','md','lg'] as const;
export default function ButtonGallery(){
 const [variant,setVariant]=useState<(typeof variants)[number]>('solid'),[size,setSize]=useState<(typeof sizes)[number]>('md'),[disabled,setDisabled]=useState(false),[full,setFull]=useState(false),[view,setView]=useState<'list'|'grid'>('list'),[message,setMessage]=useState('버튼을 눌러 동작을 확인하세요.'),[copied,setCopied]=useState(false);
 const code=`import { useState } from 'react';\nimport { Btn, ButtonLabel } from '@/components/ui/buttons';\nimport { Check } from 'lucide-react';\n\nexport default function ButtonExample() {\n  const [message, setMessage] = useState('');\n  return <>\n    <Btn variant="${variant}" size="${size}" haptic={false}${disabled?' disabled':''}${full?' full':''}\n      onClick={() => setMessage('선택됨')}>\n      <ButtonLabel icon={<Check size={15} />}>저장하기</ButtonLabel>\n    </Btn>\n    <output aria-live="polite">{message}</output>\n  </>;\n}`;
 async function copy(){try{await navigator.clipboard.writeText(code);setCopied(true)}catch{setMessage('복사하지 못했습니다. 아래 코드를 직접 선택하세요.')}}
 return <div className="button-workshop"><div className="spec-label">BUTTON WORKSHOP / ORIGINAL COMPONENTS</div><h2>버튼을 골라서 바로 사용합니다</h2><p className="workshop-note">원본의 4가지 형태 × 3가지 크기 × 사용/비활성 상태. 아래 조합은 실제 Btn 코드로 실행합니다.</p>
 <div className="workshop-controls"><label>형태<Select ariaLabel="버튼 형태" value={variant} onChange={v=>{setVariant(v as typeof variant);setCopied(false)}} options={[...variants]} full/></label><label>크기<Select ariaLabel="버튼 크기" value={size} onChange={v=>{setSize(v as typeof size);setCopied(false)}} options={[...sizes]} full/></label><label className="check-label"><Checkbox ariaLabel="버튼 비활성" checked={disabled} onChange={v=>{setDisabled(v);setCopied(false)}}/>비활성</label><label className="check-label"><Checkbox ariaLabel="가로 채우기" checked={full} onChange={v=>{setFull(v);setCopied(false)}}/>가로 채우기</label></div>
 <div className="workshop-preview"><Btn variant={variant} size={size} disabled={disabled} full={full} haptic={false} onClick={()=>setMessage(`${variant} / ${size} 선택됨`)}><ButtonLabel icon={<Check size={15}/>}>저장하기</ButtonLabel></Btn></div><output aria-live="polite" className="spec-output">{message}</output>
 <details className="workshop-code"><summary>선택한 버튼 사용 코드</summary><Btn variant="ghost" size="sm" haptic={false} onClick={copy}>{copied?'복사됨':'이 코드 복사'}</Btn><pre>{code}</pre></details>
 <h3>전체 형태 · 크기 · 상태</h3><div className="variant-grid">{variants.map(v=><section key={v}><strong>{v}</strong>{sizes.map(s=><div className="variant-row" key={s}><code>{s}</code><Btn variant={v} size={s} haptic={false} onClick={()=>setMessage(`${v} / ${s} 선택됨`)}>{v} {s}</Btn><Btn variant={v} size={s} disabled haptic={false}>{v} {s} 비활성</Btn></div>)}</section>)}</div>
 <h3>아이콘 · 선택 · 전환</h3><div className="workshop-controls"><IconBtn title="추가 예시" haptic={false} onClick={()=>setMessage('추가 버튼 선택됨')}><Plus size={16}/></IconBtn><IconBtn title="선택된 검색 예시" active haptic={false} onClick={()=>setMessage('선택된 아이콘 버튼')}><Search size={16}/></IconBtn><IconBtn title="비활성 아이콘 예시" disabled haptic={false}><Plus size={16}/></IconBtn></div><IconSeg value={view} onChange={setView} showLabel options={[{key:'list',label:'목록 보기',icon:<List size={16}/>},{key:'grid',label:'카드 보기',icon:<LayoutGrid size={16}/>} ]}/><p className="workshop-note">선택한 전환: {view==='list'?'목록':'카드'} · IconSeg는 보기 선택만 수행합니다.</p>
 <h3>링크형 · 처리 중 조합</h3><div className="workshop-controls"><Btn variant="ghost" href="#button-link-target" haptic={false}>화면 안쪽으로 이동</Btn><Btn disabled haptic={false}><LoaderCircle size={15} className="spin"/>처리 중</Btn></div><p id="button-link-target" className="workshop-note">링크형은 href로 이 예시 화면 안의 위치만 이동합니다. 처리 중은 Btn의 별도 옵션이 아닌 disabled + 아이콘 + 문구 조합입니다. 실제 요청은 하지 않습니다. lg는 원본에서 인증·손님 폼 용도입니다. 링크형 버튼의 disabled 처리와 키보드 접근성은 별도 검토 대상이므로 비활성 링크 예시는 제공하지 않습니다.</p></div>
}
