'use client';
import FormattingLab from './formatting-lab';
import {useEffect,useMemo,useState} from 'react';
import {Button,Input,NativeSelect} from './primitives';
import {fileSizeText,kmValue} from '../../../freepasserp4/lib/format';
import FunctionSearch from './function-search';
import {reuseRecipe,reuseContract} from './reuse-model';
type Module={id:string;path:string;sha256:string;category:string;language:string;functions:number;unindexedCallables:number;inspection:string;consumerPaths:string[];sameHashPaths:string[];unresolvedLocalImports:number;parseErrors:{line:number;code:string|number}[];isTest:boolean};
type Fn={id:string;moduleId:string;name:string;line:number;endLine:number;kind:string;parameters:{name:string;type:string;optional:boolean;rest:boolean}[];output:string;async:boolean};
type Project={name:string;head:string|null;dirty:boolean|null;functionCount:number;moduleCount:number;sourceFile:string};
type Summary={capturedAt:string;coverage:{projects:number;modules:number;functions:number;readErrors:number;parseErrorFiles:number;unsupportedModules:number;unindexedCallables:number;uniqueFileContents:number};limitations:string[];projects:Project[]};
type Detail={modules:Module[];functions:Fn[]};
const groups:Record<string,string>={shared:'공통 처리',conversion:'표기·변환',validation:'검증',calculation:'계산',data:'데이터 처리',integrations:'API·외부 연결',security:'인증·권한',ui:'화면·상태'};
export default function FunctionLibrary(){
 const [distance,setDistance]=useState('83,000km'),[bytes,setBytes]=useState('1048576'),[recipeCopied,setRecipeCopied]=useState('');
 const [summary,setSummary]=useState<Summary|null>(null),[project,setProject]=useState('devcenter'),[detail,setDetail]=useState<Detail|null>(null),[query,setQuery]=useState(''),[group,setGroup]=useState('all'),[mode,setMode]=useState('functions'),[limit,setLimit]=useState(40),[selected,setSelected]=useState<{module:Module;fn?:Fn}|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[copied,setCopied]=useState('');
 useEffect(()=>{let active=true;setError('');fetch('/catalog/functions-summary.json').then(r=>{if(!r.ok)throw Error('기능 목록을 불러오지 못했습니다.');return r.json()}).then(d=>{if(active){setSummary(d);setProject(p=>d.projects.some((x:Project)=>x.name===p)?p:d.projects[0]?.name||'')}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[retry]);
 const current=summary?.projects.find(p=>p.name===project);
 useEffect(()=>{let active=true;setDetail(null);setSelected(null);setLimit(40);setError('');if(!current)return;fetch(current.sourceFile).then(r=>{if(!r.ok)throw Error('선택한 프로젝트의 기능을 불러오지 못했습니다.');return r.json()}).then(d=>{if(active)setDetail(d)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[current?.sourceFile,retry]);
 const moduleMap=useMemo(()=>new Map(detail?.modules.map(m=>[m.id,m])||[]),[detail]);
 const rows=useMemo(()=>{if(!detail)return [];const source=mode==='functions'?detail.functions.map(fn=>({module:moduleMap.get(fn.moduleId)!,fn})):detail.modules.map(module=>({module,fn:undefined as Fn|undefined}));return source.filter(({module:m,fn})=>(group==='all'||m.category===group)&&`${m.path} ${fn?.name||''}`.toLowerCase().includes(query.toLowerCase()))},[detail,moduleMap,mode,group,query]);
 async function copy(){if(!selected)return;try{await navigator.clipboard.writeText(JSON.stringify({path:selected.module.path,sha256:selected.module.sha256,name:selected.fn?.name,line:selected.fn?.line,projectHead:current?.head,trackedChanges:current?.dirty,status:'static_only_not_runtime_verified'},null,2));setCopied('원본 참조 복사됨')}catch{setCopied('복사 실패: 표시된 원본 위치를 직접 선택해 주세요.')}}
 return <section aria-label="기능 창고">
  <div className="mini-card"><h2>사용처와 원본을 확인하고 가져갑니다</h2><p>입력·반환 표기와 코드 위치를 찾습니다. 기능의 업무 의미와 실행 결과는 원본에서 확인해야 합니다. 분류는 경로 기반 후보입니다.</p><a href="/function-improvements.md" target="_blank" rel="noreferrer">오류·부족·개선 기록 보기</a></div>
  <FormattingLab/><FunctionSearch select={(p,name)=>{setProject(p);setQuery(name);setGroup('all');setMode('functions');setLimit(40);setSelected(null)}}/>
  <details className="note"><summary>재사용 계약과 완결된 예제</summary><p><a href="/packages/fp4-format-preview.tgz" download>로컬 설치 시험 패키지 받기</a> · <a href="/packages/VERIFIED.json">출처와 설치 검사 근거</a></p><p>별도 JS·TS 프로젝트의 설치·실행을 검사한 시험 패키지입니다. npm 공개 배포와 운영 채택은 미진행입니다.</p>{Object.entries(reuseContract).map(([key,value])=><p key={key}>{value}</p>)}<pre className="code-block">{reuseRecipe(distance,bytes)}</pre><Button onClick={async()=>{try{await navigator.clipboard.writeText(reuseRecipe(distance,bytes));setRecipeCopied('기능 예제 복사됨')}catch{setRecipeCopied('복사 실패')}}}>기능 예제 복사</Button><p role="status">{recipeCopied}</p></details>
  <details className="note"><summary>원본 기능 직접 써보기 — 주행거리·파일 크기</summary><p>freepasserp4/lib/format.ts의 실제 함수를 빌드해 실행합니다. 아래 두 함수의 예시이며 다른 기능의 실행 검증을 의미하지 않습니다. 입력은 화면 안에서만 처리합니다.</p><label>주행거리 입력<Input aria-label="주행거리 기능 입력" value={distance} onChange={e=>setDistance(e.target.value)}/></label><output aria-label="주행거리 기능 결과">kmValue → {kmValue(distance)}</output><label>바이트 입력<Input aria-label="파일 크기 기능 입력" value={bytes} onChange={e=>setBytes(e.target.value)}/></label><output aria-label="파일 크기 기능 결과">fileSizeText → {fileSizeText(Number(bytes))||'(빈 문자열)'}</output><p className="fineprint">사용 예: 원본 프로젝트에서 import &#123; kmValue, fileSizeText &#125; from '@/lib/format'. 파일 버전은 원본 참조와 빌드의 source-manifest.json에서 확인합니다.</p></details>
  {summary&&<><div className="result-line"><span>전체 {summary.coverage.projects}개 폴더 · {summary.coverage.modules.toLocaleString()}개 코드 파일 · {summary.coverage.functions.toLocaleString()}개 함수 선언</span><span>실행 검증과 구분</span></div><div className="search-row"><NativeSelect aria-label="기능 프로젝트" value={project} onChange={e=>{setProject(e.target.value);setQuery('');setGroup('all')}}>{summary.projects.map(p=><option key={p.name} value={p.name}>{p.name} · {p.functionCount.toLocaleString()}개 함수</option>)}</NativeSelect><NativeSelect aria-label="기능 그룹" value={group} onChange={e=>{setGroup(e.target.value);setLimit(40);setSelected(null)}}><option value="all">모든 그룹</option>{Object.entries(groups).map(([id,label])=><option key={id} value={id}>{label}</option>)}</NativeSelect><NativeSelect aria-label="기능 표시 방식" value={mode} onChange={e=>{setMode(e.target.value);setLimit(40);setSelected(null)}}><option value="functions">함수 선언</option><option value="modules">모듈·스크립트</option></NativeSelect><Input aria-label="기능 검색" placeholder="선택한 프로젝트의 함수·경로 검색" value={query} onChange={e=>{setQuery(e.target.value);setLimit(40);setSelected(null)}}/></div><p className="fineprint">선택 프로젝트 버전 {current?.head?.slice(0,12)||'Git 버전 미확인'} · 추적 파일 변경 {current?.dirty===null?'미확인':current?.dirty?'있음':'없음'} · 원본 해시는 파일별로 확인하세요.</p></>}
  {error?<div className="error-box" role="alert">{error}<Button onClick={()=>setRetry(v=>v+1)}>다시 불러오기</Button></div>:!detail?<p role="status">기능 목록을 불러오는 중입니다.</p>:<><div className="result-line">선택 범위 {rows.length.toLocaleString()}건</div><div className={`catalog-layout ${selected?'has-detail':''}`}><div>{rows.slice(0,limit).map(row=><button className="doc-row" key={row.fn?.id||row.module.id} onClick={()=>{setSelected(row);setCopied('')}}><span><strong>{row.fn?.name||row.module.path.split('/').pop()}</strong><code>{row.module.path}{row.fn?`:${row.fn.line}`:''}</code></span><span className="life">{groups[row.module.category]} · {row.fn?'선언 발견':`${row.module.functions}개 함수`}</span></button>)}{!rows.length&&<div className="empty"><h3>일치하는 기능이 없습니다.</h3><p>다른 단어·그룹·프로젝트 또는 모듈 표시를 선택하세요.</p><Button onClick={()=>{setQuery('');setGroup('all')}}>검색 초기화</Button></div>}{rows.length>limit&&<Button onClick={()=>setLimit(v=>v+40)}>40개 더 보기</Button>}</div>{selected&&<aside className="doc-detail"><Button variant="ghost" onClick={()=>setSelected(null)}>닫기</Button><h3>{selected.fn?.name||'모듈 원본'}</h3><code className="path">{selected.module.path}</code><p className="fineprint">파일 원문 SHA {selected.module.sha256}</p><p>{selected.module.inspection==='file_only_unsupported_parser'?'파일 위치만 등록 · 함수 해석 미지원':'정적 선언 확인 · 실행 미검증'}</p>{selected.fn&&<><h4>입력</h4>{selected.fn.parameters.length?selected.fn.parameters.map((p,i)=><p key={i}>{p.rest?'...':''}{p.name}{p.optional?' (생략 가능)':''} · {p.type}</p>):<p>선언된 매개변수 없음</p>}<h4>반환 표기</h4><p>{selected.fn.output} {selected.fn.async?'· 비동기':''}</p><p className="fineprint">본문 추론을 수행하지 않았습니다. 미명시는 오류를 뜻하지 않습니다. 업무 단위·예외·부작용은 원문 확인 대상입니다.</p></>}<p className="fineprint">익명 콜백 등 목록에 따로 등록하지 않은 함수 {selected.module.unindexedCallables}개. 원본 전체를 함께 확인하세요.</p><h4>이 모듈을 직접 참조한 파일</h4>{selected.module.consumerPaths.length?selected.module.consumerPaths.map(p=><code className="path" key={p}>{p}</code>):<p>연결된 상대경로 참조 없음. 미사용 판정은 아닙니다.</p>}<p className="fineprint">모듈 import 근거이며 선택한 함수의 호출·실행 증거는 아닙니다. 이 모듈의 미해결 로컬 import {selected.module.unresolvedLocalImports}건.</p>{!!selected.module.parseErrors.length&&<div className="note">구문 확인 과제 {selected.module.parseErrors.map(e=>`L${e.line} (${e.code})`).join(', ')}. 프로젝트의 실제 빌드로 재확인해야 합니다.</div>}{!!selected.module.sameHashPaths.length&&<details><summary>같은 내용의 파일 후보 {selected.module.sameHashPaths.length}개</summary>{selected.module.sameHashPaths.map(p=><code className="path" key={p}>{p}</code>)}<p>같은 해시는 통합·삭제 승인 근거가 아닙니다.</p></details>}<Button variant="outline" onClick={copy}>원본 참조 복사</Button><p role="status">{copied}</p></aside>}</div></>}
  {summary&&<details className="note"><summary>조사 범위·미확인 항목</summary><p>{summary.capturedAt} · 읽기 오류 {summary.coverage.readErrors}건 · 구문 진단 파일 {summary.coverage.parseErrorFiles}개 · 파일만 등록 {summary.coverage.unsupportedModules}개 · 미등록 콜백 등 {summary.coverage.unindexedCallables?.toLocaleString()}개 · 서로 다른 파일 내용 {summary.coverage.uniqueFileContents?.toLocaleString()}개</p><ul>{summary.limitations.map(s=><li key={s}>{s}</li>)}</ul></details>}
 </section>
}
