'use client';
import {useEffect,useState} from 'react';
import {Button,Input,NativeSelect} from './primitives';
import {checkPlan,gradeQuestions,historyKey,mergeHistory,parseHistory,planFields,type LearningArchive,type LearningRecord,type Question,type WorkPlan} from './learning-model';
export default function LearningHistory({questions,questionVersion,answers,plan}:{questions:Question[];questionVersion:string;answers:Record<string,number>;plan:Partial<WorkPlan>}){
 const [archive,setArchive]=useState<LearningArchive>({version:1,records:[]}),[session,setSession]=useState(''),[outcome,setOutcome]=useState<LearningRecord['outcome']>('not-run'),[evidence,setEvidence]=useState(''),[transfer,setTransfer]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[backups,setBackups]=useState<string[]>([]);
 const read=()=>parseHistory(localStorage.getItem(historyKey)||'{"version":1,"records":[]}',questions,questionVersion);
 useEffect(()=>{function refresh(){try{setBackups(Object.keys(localStorage).filter(k=>k.startsWith(historyKey+'.backup.')).sort().reverse())}catch{}try{setArchive(read());setReady(true);setError('')}catch(e){setReady(false);setError(String((e as Error).message))}}refresh();const changed=(e:StorageEvent)=>{if(e.key===historyKey||e.key===null)refresh()};window.addEventListener('storage',changed);return()=>window.removeEventListener('storage',changed)},[questions,questionVersion]);
 async function persist(incoming:LearningArchive){setBusy(true);setError('');setMessage('');try{
  if(!navigator.locks)throw Error('저장에는 HTTPS 또는 localhost와 Web Locks 지원 브라우저가 필요합니다.');
  await navigator.locks.request(historyKey,()=>{const merged=mergeHistory(read(),incoming);const raw=JSON.stringify(merged);parseHistory(raw,questions,questionVersion);localStorage.setItem(historyKey,raw);setArchive(merged);setReady(true)});setMessage('이 브라우저에 이력 저장됨 · 승인 아님');
 }catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function save(kind:LearningRecord['kind']){try{if(!session.trim())throw Error('세션 이름을 입력하세요.');if(!crypto.randomUUID)throw Error('저장에는 HTTPS 또는 localhost 접속이 필요합니다.');const record:LearningRecord={id:crypto.randomUUID(),session:session.trim(),createdAt:new Date().toISOString(),questionVersion,kind,answers:kind==='learning'?{...answers}:{},plan:kind==='practice'?{...plan}:{},outcome:kind==='practice'?outcome:'not-run',evidence:kind==='practice'?evidence:''};const incoming=parseHistory(JSON.stringify({version:1,records:[record]}),questions,questionVersion);void persist(incoming)}catch(e){setError((e as Error).message)}}
 async function exportHistory(){try{const raw=localStorage.getItem(historyKey)||'{"version":1,"records":[]}';setTransfer(raw);setMessage('저장 원문을 아래 JSON 칸에 표시했습니다. 선택하여 복사할 수 있습니다.');if(navigator.clipboard){await navigator.clipboard.writeText(raw);setMessage('저장 원문 복사됨 · 민감 내용이 없는지 확인 후 전달하세요.')}}catch(e){setError((e as Error).message)}}
 async function startBundle(){setBusy(true);setError('');try{if(!navigator.locks)throw Error('새 묶음 시작에는 Web Locks가 필요합니다.');await navigator.locks.request(historyKey,()=>{const raw=localStorage.getItem(historyKey);if(raw!==null){const key=historyKey+'.backup.'+crypto.randomUUID();localStorage.setItem(key,raw);setBackups(b=>[key,...b]);}localStorage.setItem(historyKey,JSON.stringify({version:1,records:[]}));setArchive({version:1,records:[]});setReady(true)});setMessage('이전 원문을 브라우저 백업으로 보존하고 새 묶음을 시작했습니다.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const relearn=archive.records.filter(r=>r.questionVersion!==questionVersion||r.kind==='learning'&&gradeQuestions(questions,r.answers).correct<questions.length||r.kind==='practice'&&r.outcome!=='passed');
 return <section className="mini-card learning-panel" style={{marginTop:24}} aria-label="세션 학습 이력"><h2>세션별 학습·실습 이력</h2><p>이 브라우저에 최대 200건을 보관합니다. 세션 이름·실행 결과·시각은 본인 기록이며 독립 검수 증거가 아닙니다. 다른 브라우저에는 JSON을 복사해서 가져오세요. 브라우저 저장소를 지우면 사라집니다. 비밀번호·고객정보를 입력하지 마세요.</p>
 <label>세션 이름<Input aria-label="이력 세션 이름" required maxLength={120} value={session} onChange={e=>setSession(e.target.value)}/></label>
 <p><Button disabled={!ready||busy} onClick={()=>save('learning')}>현재 답안 이력 저장</Button></p>
 <label>실습 실행 결과<NativeSelect aria-label="실습 실행 결과" value={outcome} onChange={e=>setOutcome(e.target.value as LearningRecord['outcome'])}><option value="not-run">아직 실행하지 않음</option><option value="passed">직접 실행 성공 · 검수 대기</option><option value="failed">직접 실행 실패 · 보완 필요</option></NativeSelect></label>
 <label style={{display:'block',marginTop:12}}>실행 근거 위치와 관찰 결과<textarea className="ui-input" aria-label="실습 실행 근거" maxLength={4000} rows={3} value={evidence} onChange={e=>setEvidence(e.target.value)}/></label><p>위 실습 양식의 6개 칸을 작성한 뒤 저장하세요. 미실행 계획도 검토 대기로 보관할 수 있습니다.</p><Button disabled={!ready||busy} onClick={()=>save('practice')}>현재 실습 이력 저장</Button>
 {error&&<p role="alert">{error} 저장 원문은 자동으로 덮어쓰거나 삭제하지 않습니다.</p>}{message&&<p role="status">{message}</p>}
 <p>접수 경로와 작성자 신원은 검증하지 않습니다. 아래 시각은 작성자가 제공한 기록 시각입니다.</p><h3>보관 {archive.records.length}건 · 재학습·보완 대상 {relearn.length}건</h3><p>자가 보고 성공 · 미검수 {archive.records.filter(r=>r.kind==='practice'&&r.outcome==='passed').length}건 · 모든 실습의 실무 승인 대기 {archive.records.filter(r=>r.kind==='practice').length}건</p><p>문제 버전 변경, 오답·미응답, 미실행·실패 실습을 표시합니다. 성공을 기록해도 정본 확인·실무 승인은 별도입니다.</p>
 {[...archive.records].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(r=>{const current=r.questionVersion===questionVersion,score=current&&r.kind==='learning'?gradeQuestions(questions,r.answers):null;return <details key={r.id}><summary>{r.session} · {r.kind==='learning'?'학습':'실습'} · {r.createdAt} · {!current?'문제 버전 변경 · 재학습 필요':score?`정답 ${score.correct}/${score.total}`:r.outcome==='passed'?'실행 성공 기록 · 검수 대기':r.outcome==='failed'?'실패 · 보완 필요':'미실행 · 검토 대기'}</summary><p>원본 확인 미검증 · 승인 대기 · 이력 ID {r.id}</p><code className="path">문제 버전 {r.questionVersion}</code>{score&&<p>다시 볼 카드: {score.results.filter(s=>!s.correct).map(s=>s.cardId).join(', ')||'오답 없음 · 실무 검수 별도'}</p>}{r.kind==='practice'&&<><dl>{Object.entries(planFields).map(([k,label])=><div key={k}><dt>{label}</dt><dd style={{overflowWrap:'anywhere',whiteSpace:'pre-wrap'}}>{r.plan[k as keyof WorkPlan]}</dd></div>)}</dl><p>실행 근거: {r.evidence||'없음'}</p><p>계획 필수 칸: {checkPlan(r.plan).readyForReview?'작성됨':'누락'}</p></>}</details>})}
 <details><summary>다른 세션에 전달·가져오기</summary><p>가져온 기록은 자가 기록으로 취급합니다. 점수·승인 필드는 받지 않으며 현재 문제의 답안만 다시 채점합니다. 기존 ID의 내용이 다르면 합치지 않습니다.</p><Button onClick={exportHistory}>저장 이력 원문 복사</Button><textarea className="ui-input" aria-label="가져올 학습 이력 JSON" rows={5} maxLength={1000000} value={transfer} onChange={e=>setTransfer(e.target.value)}/><Button disabled={!ready||busy} onClick={()=>{try{void persist(parseHistory(transfer,questions,questionVersion))}catch(e){setError((e as Error).message)}}}>검사 후 이력 합치기</Button></details>
 <details><summary>가득 찼거나 손상된 이력 보관하기</summary><p>현재 원문을 별도 브라우저 백업으로 남기고 빈 이력 묶음을 시작합니다. 기존 기록을 삭제하지 않습니다. 브라우저 용량이 부족하면 실행되지 않으므로 먼저 원문을 외부 파일로 보관하세요. 백업도 이 브라우저를 지우면 사라집니다.</p><Button disabled={busy} onClick={startBundle}>원문 백업 후 새 묶음 시작</Button>{backups.map(key=><p key={key}><Button onClick={()=>{try{setTransfer(localStorage.getItem(key)||'');setMessage('백업 원문을 전달·가져오기 JSON 칸에 표시했습니다.')}catch(e){setError((e as Error).message)}}}>백업 원문 보기 {key.slice(-8)}</Button></p>)}</details>
 </section>
}
