import {useEffect,useMemo,useState} from 'react';
import {Search,Copy,FileCode2} from 'lucide-react';
import {Button,Input,NativeSelect} from './primitives';
type StyleFile={id:string;project:string;path:string;sha256:string;displaySha256?:string;lineCount:number;selectors:{line:number;text:string}[];variables:{line:number;text:string}[];source:string;sourceStatus:string;sourceFile:string;hasSource:boolean};
type InlineFile={id:string;project:string;path:string;sha256:string;markerCount:number;sourceFile:string;markers:{line:number;kind:string;text:string}[]};
type StyleData={capturedAt:string;coverage:Record<string,number>;files:StyleFile[];duplicates:{sha256:string;paths:string[]}[];inlineStyles?:InlineFile[];limitations:string[]};
export default function StylesLibrary(){
 const [data,setData]=useState<StyleData|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[project,setProject]=useState('all'),[selected,setSelected]=useState<StyleFile|null>(null),[limit,setLimit]=useState(40),[copied,setCopied]=useState(false),[retry,setRetry]=useState(0),[sourceError,setSourceError]=useState(''),[sourceLoading,setSourceLoading]=useState(false),[sourceRequest,setSourceRequest]=useState(0);
 useEffect(()=>{let active=true;if(!selected)return;setSourceLoading(true);setSourceError('');fetch(selected.sourceFile).then(r=>{if(!r.ok)throw Error('원문을 불러오지 못했습니다. 다시 선택하세요.');return r.json()}).then(d=>{if(active)setSelected(prev=>prev?{...prev,...d}:prev)}).catch(e=>{if(active)setSourceError(e.message)}).finally(()=>{if(active)setSourceLoading(false)});return()=>{active=false}},[selected?.id,sourceRequest]);
 useEffect(()=>{let active=true;setError('');fetch('/catalog/styles.json').then(r=>{if(!r.ok)throw Error('CSS 조사 자료를 불러오지 못했습니다.');return r.json()}).then(d=>{if(active)setData(d)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[retry]);
 const filtered=useMemo(()=>data?.files.filter(f=>(project==='all'||f.project===project)&&`${f.path} ${f.selectors.map(x=>x.text).join(' ')} ${f.variables.map(x=>x.text).join(' ')}`.toLowerCase().includes(query.toLowerCase()))||[],[data,query,project]);
 if(error)return <div className="error-box">{error}<Button onClick={()=>setRetry(v=>v+1)}>다시 불러오기</Button></div>;
 if(!data)return <div className="loading">CSS 원본과 중복을 조사한 자료를 불러옵니다.</div>;
 const duplicate=selected?data.duplicates.find(x=>x.sha256===selected.sha256):null;
 async function copy(){if(!selected)return;try{await navigator.clipboard.writeText(selected.source);setCopied(true)}catch{setCopied(false)}}
 return <><div className="principle-banner"><FileCode2/><div><strong>CSS 원본을 찾고, 적용 범위를 확인하세요.</strong><p>{data.files.length.toLocaleString()}개 스타일 파일 · 동일 내용 묶음 {data.duplicates.length.toLocaleString()}개. 같은 내용이어도 원본 위치를 임의로 합치지 않습니다.</p></div></div><div className="note prominent">프로젝트 CSS 전체를 다른 화면에 그대로 넣으면 클래스·전역 스타일이 충돌할 수 있습니다. 아래 코드는 해당 프로젝트의 원본 스냅샷입니다. 공용 버튼은 원자 실험실의 컴포넌트로 사용하세요.</div>
 <div className="search-row"><div className="search-field"><Search size={17}/><Input aria-label="CSS 검색" placeholder="파일·선택자·CSS 변수 검색" value={query} onChange={e=>{setQuery(e.target.value);setLimit(40)}}/></div><NativeSelect aria-label="CSS 프로젝트" value={project} onChange={e=>{setProject(e.target.value);setLimit(40)}}><option value="all">모든 프로젝트</option>{[...new Set(data.files.map(f=>f.project))].sort().map(p=><option key={p}>{p}</option>)}</NativeSelect></div><div className="result-line"><b>{filtered.length}개 파일</b><span>읽기 전용 원본 보기 · 원문 SHA 연결</span></div>
 <div className={`catalog-layout ${selected?'has-detail':''}`}><div>{filtered.slice(0,limit).map(f=><button key={f.id} className={`doc-row ${selected?.id===f.id?'active':''}`} onClick={()=>{setSelected(f);setSourceRequest(n=>n+1);setCopied(false)}}><FileCode2 size={17}/><span><strong>{f.path.split('/').pop()}</strong><code>{f.path}</code></span><span className="life">{f.lineCount}행</span></button>)}{!filtered.length&&<div className="empty"><h3>일치하는 CSS가 없습니다.</h3><Button onClick={()=>{setQuery('');setProject('all')}}>필터 해제</Button></div>}{filtered.length>limit&&<Button className="load-more" variant="outline" onClick={()=>setLimit(v=>v+40)}>40개 더 보기</Button>}</div>
 {selected&&<aside className="doc-detail"><div className="detail-top"><strong>CSS 표시본</strong><Button variant="ghost" onClick={()=>setSelected(null)}>닫기</Button></div><code className="path">{selected.path}</code><div className="detail-meta">원본 SHA {selected.sha256.slice(0,16)} · {selected.sourceStatus==="included"?"원문 전체":"가림 또는 표시 제한"}</div>{duplicate&&<details><summary>동일 해시의 파일 {duplicate.paths.length}개</summary>{duplicate.paths.map(p=><code key={p} className="path">{p}</code>)}</details>}{selected.sourceStatus!=="included"&&<div className="note">외부 주소·내장 데이터 등이 가려지거나 표시가 제한된 자료입니다. 복사본은 원본과 다를 수 있습니다.</div>}<h4>CSS 변수</h4>{selected.variables.slice(0,20).map((v,i)=><div className="excerpt" key={i}><b>L{v.line}</b><code>{v.text}</code></div>)}{!selected.variables.length&&<p className="fineprint">추출된 사용자 정의 변수가 없습니다.</p>}<div className="code-toolbar"><span>표시본 SHA {selected.displaySha256?.slice(0,12)}</span><Button variant="outline" size="sm" onClick={copy} disabled={sourceLoading||!selected.source}><Copy size={13}/>{copied?'복사됨':selected.sourceStatus==='included'?'코드 복사':'가림본 복사'}</Button></div><pre className="code-block full-source">{sourceLoading?'선택한 파일을 불러옵니다.':sourceError||selected.source||'이 파일은 원문 표시 범위에서 제외됐습니다. 원본 경로에서 확인하세요.'}</pre></aside>}</div><InlineStyles files={data.inlineStyles||[]}/><details className="note" style={{marginTop:20}}><summary>수집 범위와 제한</summary><ul>{data.limitations.map(x=><li key={x}>{x}</li>)}</ul><p>수집 시각 {data.capturedAt}</p></details></>
}
function InlineStyles({files}:{files:InlineFile[]}){
 const [query,setQuery]=useState(''),[selected,setSelected]=useState<InlineFile|null>(null),[limit,setLimit]=useState(20),[loading,setLoading]=useState(false),[error,setError]=useState(''),[sourceRequest,setSourceRequest]=useState(0);
 useEffect(()=>{let active=true;if(!selected)return;setLoading(true);setError('');fetch(selected.sourceFile).then(r=>{if(!r.ok)throw Error('스타일 위치를 불러오지 못했습니다. 다시 선택하세요.');return r.json()}).then(d=>{if(active)setSelected(p=>p?{...p,markers:d.markers}:p)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[selected?.id,sourceRequest]);
 const matches=files.filter(f=>f.path.toLowerCase().includes(query.toLowerCase()));
 return <section style={{marginTop:30}}><div className="section-heading"><div><h2>코드 안에 작성된 스타일</h2><p>JS/TS 파일 {files.length.toLocaleString()}개의 후보 위치. 실제 CSS 의미와 적용 여부는 원본 대조가 필요합니다.</p></div></div><Input aria-label="인라인 스타일 검색" placeholder="프로젝트·파일 경로로 검색" value={query} onChange={e=>{setQuery(e.target.value);setLimit(20)}}/><div className="result-line">{matches.length}개 파일</div><div className={`catalog-layout ${selected?'has-detail':''}`}><div>{matches.slice(0,limit).map(f=><button className="doc-row" key={f.id} onClick={()=>{setSelected(f);setSourceRequest(n=>n+1)}}><FileCode2 size={17}/><span><strong>{f.path.split('/').pop()}</strong><code>{f.path}</code></span><span className="life">{f.markerCount}개 위치</span></button>)}{!matches.length&&<p className="note">해당 경로에 일치하는 후보가 없습니다.</p>}{matches.length>limit&&<Button variant="outline" onClick={()=>setLimit(n=>n+20)}>20개 더 보기</Button>}</div>{selected&&<aside className="doc-detail"><Button variant="ghost" onClick={()=>setSelected(null)}>닫기</Button><code className="path">{selected.path}</code><p className="fineprint">원본 SHA {selected.sha256.slice(0,16)} · 문맥이 생략된 위치 발췌</p>{loading?<p>발췌를 불러옵니다.</p>:error?<p>{error}</p>:selected.markers.map((m,i)=><div className="excerpt" key={i}><b>L{m.line}</b><code>{m.kind}: {m.text}</code></div>)}</aside>}</div></section>
}
