'use client';
import {useEffect,useMemo,useState} from 'react';
import {Button,Input,NativeSelect} from './primitives';
type Asset={id:string;name:string;project:string;path:string;line:number;sha256:string;group:string;part:string;kind:string};
type Use={path:string;project:string;sha256:string;section:string;version:string};
type Data={capturedAt:string;coverage:Record<string,number>;projects:{name:string}[];assets:Asset[];packages:{name:string;uses:Use[]}[];manifests:{path:string;project:string;scriptNames:string[]}[];limitations:string[];issues:{path:string;reason:string}[]};
export default function Toolbox(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[mode,setMode]=useState('symbols'),[query,setQuery]=useState(''),[project,setProject]=useState('all'),[part,setPart]=useState('all'),[selected,setSelected]=useState<Asset|null>(null),[limit,setLimit]=useState(40),[copied,setCopied]=useState('');
 useEffect(()=>{const controller=new AbortController();setError('');fetch('/catalog/toolbox.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error('도구 목록을 불러오지 못했습니다.');return r.json()}).then(d=>{if(!Array.isArray(d.assets)||!Array.isArray(d.packages)||!Array.isArray(d.manifests)||!d.coverage||!Array.isArray(d.projects)||!Array.isArray(d.limitations)||!Array.isArray(d.issues))throw Error('도구 목록 형식이 잘못되었습니다.');setData(d)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)});return()=>controller.abort()},[retry]);
 const assets=useMemo(()=>data?.assets.filter(a=>(project==='all'||a.project===project)&&(part==='all'||a.part===part)&&`${a.name} ${a.path} ${a.group}`.toLowerCase().includes(query.toLowerCase()))||[],[data,project,part,query]);
 const packages=useMemo(()=>data?.packages.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())&&p.uses.some(u=>project==='all'||u.project===project))||[],[data,query,project]);
 if(error)return <div role="alert" className="error-box">{error}<Button onClick={()=>setRetry(n=>n+1)}>도구 목록 다시 읽기</Button></div>;if(!data)return <p role="status">프로젝트의 부품과 도구를 찾는 중입니다.</p>;
 function reset(){setQuery('');setPart('all');setProject('all');setLimit(40);setSelected(null)}
 const count=mode==='symbols'?assets.length:mode==='packages'?packages.length:data.manifests.filter(m=>(project==='all'||m.project===project)&&m.path.toLowerCase().includes(query.toLowerCase())).length;
 return <section aria-label="프로젝트 도구 모음"><div className="metrics">{[['공개 부품·함수·훅',data.coverage.publicSymbols],['의존 도구 종류',data.coverage.packages],['패키지 선언 파일',data.coverage.manifests],['변경·누락·제외',data.coverage.changed+data.coverage.missing+data.coverage.linked+data.coverage.outside]].map(([label,n])=><div key={label}><span>{label}</span><strong>{Number(n).toLocaleString()}</strong></div>)}</div><p className="note">원본이 있는 곳으로 연결하는 창고입니다. 공개 심볼은 재사용 후보, 도구는 의존성 선언입니다. 설치·동작·승인 여부를 별도로 확인하세요.</p>
 <div className="search-row"><NativeSelect aria-label="도구 모음 종류" value={mode} onChange={e=>{setMode(e.target.value);reset()}}><option value="symbols">공개 부품·함수·훅</option><option value="packages">프로젝트의 개발 도구</option><option value="scripts">빌드·검사 명령 이름</option></NativeSelect><Input aria-label="도구 모음 검색" placeholder="버튼, Dialog, chart, zod…" value={query} onChange={e=>{setQuery(e.target.value);setLimit(40)}}/><NativeSelect aria-label="도구 모음 프로젝트" value={project} onChange={e=>{setProject(e.target.value);setLimit(40)}}><option value="all">모든 프로젝트</option>{data.projects.map(p=><option key={p.name}>{p.name}</option>)}</NativeSelect>{mode==='symbols'&&<NativeSelect aria-label="도구 모음 파트" value={part} onChange={e=>{setPart(e.target.value);setLimit(40)}}><option value="all">모든 파트</option>{[...new Set(data.assets.map(a=>a.part))].sort().map(p=><option key={p}>{p}</option>)}</NativeSelect>}</div><p role="status">검색 결과 {count.toLocaleString()}개</p>
 {!count&&<div className="empty"><p>일치하는 도구가 없습니다.</p><Button onClick={reset}>도구 필터 초기화</Button></div>}
 {mode==='symbols'&&<div className="catalog-layout has-detail"><div>{assets.slice(0,limit).map(a=><button className="doc-row" key={a.id} onClick={()=>{setSelected(a);setCopied('')}}><span><strong>{a.name}</strong><code>{a.path}:{a.line}</code><small>{a.group} / {a.part} · 후보</small></span></button>)}</div>{selected&&<aside className="doc-detail"><h2>{selected.name}</h2><p>{selected.group} → {selected.part}</p><code className="path">{selected.path}:{selected.line}</code><p>원본 SHA {selected.sha256}</p><p>선언 형태: {selected.kind}. 재수출은 이 경로가 구현 원본이 아닐 수 있습니다.</p><p>이 심볼의 입력·의존성·부작용·접근성을 원문에서 확인한 뒤 사용합니다. 이름만으로 실행 예제를 만들지 않습니다.</p><Button onClick={async()=>{try{await navigator.clipboard.writeText(JSON.stringify({recordType:'reuse_candidate',...selected,approval:'pending'},null,2));setCopied('도구 원본 참조 복사됨')}catch{setCopied('복사 실패')}}}>도구 원본 참조 복사</Button><p role="status">{copied}</p></aside>}</div>}
 {mode==='packages'&&packages.slice(0,limit).map(p=><details className="mini-card" key={p.name}><summary>{p.name} · {p.uses.filter(u=>project==='all'||u.project===project).length}개 선언</summary><p>선언 버전 범위이며 실제 설치 버전·라이선스 검증은 미완료입니다.</p>{p.uses.filter(u=>project==='all'||u.project===project).map((u,i)=><p key={i}><code>{u.path}</code><br/>{u.section} · {u.version}<br/>SHA {u.sha256}</p>)}</details>)}
 {mode==='scripts'&&data.manifests.filter(m=>(project==='all'||m.project===project)&&m.path.toLowerCase().includes(query.toLowerCase())).slice(0,limit).map(m=><article className="mini-card" key={m.path}><h3>{m.path}</h3><p>{m.scriptNames.join(' · ')||'등록된 명령 없음'}</p><p>명령 이름만 표시합니다. 실행 전 원본 package.json을 확인하세요.</p></article>)}
 {count>limit&&<Button onClick={()=>setLimit(n=>n+40)}>도구 40개 더 보기</Button>}
 <details className="mini-card"><summary>조사 범위와 미수집 항목</summary><p>수집 시각 {data.capturedAt} · 원본 해시 재대조 {data.coverage.current}/{data.coverage.modules}</p>{data.limitations.map(l=><p key={l}>{l}</p>)}{data.issues.slice(0,50).map((x,i)=><p key={i}>{x.path} · {x.reason}</p>)}<a href="/catalog/toolbox.json" download>전체 색인·예외 목록 내려받기</a></details></section>
}
